#!/bin/bash

#   Different ways to discover the IP address
#   by MAC address in a LAN

#   first parameters :
#   1   Using nbtscan -r
#   2   Using nmap -sn
#   3   Using fping -g and arp -a

#   second parameters :
#   1   2
#   3   4
#
#   5   6
#   7   8
#
#   9  10
#  11  12

#arp -s 115.155.46.126 00:1A:A9:15:77:09

#   local area network
#LAN="115.155.46.0/25"
#LAN="10.170.0.0/16"
LAN="210.27.11.0/24"

#   MAC address
MAC=("" "b8:70:f4:4a:f4:ee" "e8:9a:8f:2f:e3:ef" "14:da:e9:61:0c:7e" "54:04:a6:ae:00:ec" "10:78:d2:6a:a0:28" "84:8f:69:d2:cb:4a" "f0:de:f1:5c:0c:4e" "b8:88:e3:7b:80:ce" "14:fe:b5:c4:1e:74" "ac:22:0b:d7:59:5c" "04:7d:7b:fb:84:19" "04:7d:7b:2d:13:45")
VICTIM_MAC=${MAC[$2]}

if [ $1 == 1 ] ; then
    echo "[+]"
    echo "[+] Using nbtscan"
    VICTIM_IP=`nbtscan -r $LAN | grep $VICTIM_MAC | cut -d" " -f1`
elif [ $1 == 2 ] ; then
    echo "[+]"
    echo "[+] Using nmap"
    VICTIM_IP=`
      nmap -sn $LAN |
      grep -iB 2 $VICTIM_MAC |
      head -1 |
      awk -F " " '{print $NF}'
    `
elif [ $1 == 3 ] ; then 
    echo "[+]"
    echo "[+] Using fping and arp"
#    fping -g $LAN > /dev/null 2>&1
    fping -g $LAN
    VICTIM_IP=`
      arp -a |
      grep -i "$VICTIM_MAC" |
      awk -F " " '{print $2}' |
      sed 's/.*(//g;s/).*//g'
    `
    VICTIM_IP=`
      arp -a |
      grep -i "$VICTIM_MAC" |
      awk -F " " '{print $2}' |
      sed 's/.*(//g;s/).*//g'
    `
fi

sleep 1

if [ -z "$VICTIM_IP" ] ; then
    echo "[+]"
    echo "[-] victim is down"
    echo -n "[-] "
    date
    sleep 1
else
    echo "[+]"
    echo "[+] victim is up"
    echo -n "[+] "
    date
    sleep 1
    echo "[+]"
    echo "[+] $VICTIM_MAC : $VICTIM_IP"
fi
echo "[ ]"

