#define RegisterClassEx
#define CreateWindowEx
#define FindWindowEx
#define GetClassInfoEx
#define GetClassNameEx
#define UnregisterClassEx
#define WindowProcEx
#define WNDCLASSEX

// user32.lib
#define BeginPaint
#define CallWindowProcA
#define ChangeDisplaySettingsA
#define CloseClipboard
#define CreateWindowExA
#define DefWindowProcA
#define DeleteMenu
#define DrawText
#define EmptyClipboard
#define EnableWindow
#define EndPaint
#define EnunDisplaySettingsA
#define ExitWindowsEx
#define FillRect
#define FindWindowA
#define GetAsyncKeyState
#define GetClientRect
#define GetCursorPos
#define GetDC
#define GetDesktopWindow
#define GetSysColor
#define GetSysColorBrush
#define GetSystemMenu
#define GetSystemMetrics
#define GetWindow
#define GetWindowLongA
#define GetWindowRect
#define GetWindowTextA
#define GetWindowTextLengthA
#define GetWindowWord
#define MoveWindow
#define OpenClipboard
#define PostMessageA
#define ReleaseDC
#define SendMessageA
#define SetClipboardData
#define SetLayeredWindowAttributes
#define SetParent
#define SetSysColors
#define SetWindowLongA
#define SetWindowPos
#define ShowWindow
#define SystemParametersInfoA
// user32.lib end