// user32.lib start
#define ActivateKeyboardLayout
#define AddClipboardFormatListener
#define AdjustWindowRect
#define AdjustWindowRectEx
#define AllowSetForegroundWindow
#define AnimateWindow
#define AnyPopup
#define AppendMenu
#define AppendMenu
#define ArrangeIconicWindows
#define AttachThreadInput
#define BeginDeferWindowPos
#define BeginPaint
#define BlockInput
#define BringWindowToTop
#define BroadcastSystemMessage
#define BroadcastSystemMessage
#define BroadcastSystemMessageEx
#define BroadcastSystemMessageEx
#define BroadcastSystemMessage
#define CalculatePopupWindowPosition
#define CallMsgFilter
#define CallMsgFilter
#define CallMsgFilter
#define CallNextHookEx
#define CallWindowProc
#define CallWindowProc
#define CancelShutdown
#define CascadeChildWindows
#define CascadeWindows
#define ChangeClipboardChain
#define ChangeDisplaySettings
#define ChangeDisplaySettingsEx
#define ChangeDisplaySettingsEx
#define ChangeDisplaySettings
#define ChangeMenu
#define ChangeMenu
#define ChangeWindowMessageFilter
#define ChangeWindowMessageFilterEx
#define CharLower
#define CharLowerBuff
#define CharLowerBuff
#define CharLower
#define CharNext
#define CharNextEx
#define CharNext
#define CharPrev
#define CharPrevEx
#define CharPrev
#define CharToOem
#define CharToOemBuff
#define CharToOemBuff
#define CharToOem
#define CharUpper
#define CharUpperBuff
#define CharUpperBuff
#define CharUpper
#define CheckDlgButton
#define CheckMenuItem
#define CheckMenuRadioItem
#define CheckRadioButton
#define ChildWindowFromPoint
#define ChildWindowFromPointEx
#define ClientToScreen
#define ClipCursor
#define CloseClipboard
#define CloseDesktop
#define CloseGestureInfoHandle
#define CloseTouchInputHandle
#define CloseWindow
#define CloseWindowStation
#define CopyAcceleratorTable
#define CopyAcceleratorTable
#define CopyIcon
#define CopyImage
#define CopyRect
#define CountClipboardFormats
#define CreateAcceleratorTable
#define CreateAcceleratorTable
#define CreateCaret
#define CreateCursor
#define CreateDesktop
#define CreateDesktopEx
#define CreateDesktopEx
#define CreateDesktop
#define CreateDialogIndirectParam
#define CreateDialogIndirectParam
#define CreateDialogParam
#define CreateDialogParam
#define CreateIcon
#define CreateIconFromResource
#define CreateIconFromResourceEx
#define CreateIconIndirect
#define CreateMDIWindow
#define CreateMDIWindow
#define CreateMenu
#define CreatePopupMenu
#define CreateWindowEx
#define CreateWindowEx
#define CreateWindowStation
#define CreateWindowStation
#define DdeAbandonTransaction
#define DdeAccessData
#define DdeAddData
#define DdeClientTransaction
#define DdeCmpStringHandles
#define DdeConnect
#define DdeConnectList
#define DdeCreateDataHandle
#define DdeCreateStringHandle
#define DdeCreateStringHandle
#define DdeDisconnect
#define DdeDisconnectList
#define DdeEnableCallback
#define DdeFreeDataHandle
#define DdeFreeStringHandle
#define DdeGetData
#define DdeGetLastError
#define DdeImpersonateClient
#define DdeInitialize
#define DdeInitialize
#define DdeKeepStringHandle
#define DdeNameService
#define DdePostAdvise
#define DdeQueryConvInfo
#define DdeQueryNextServer
#define DdeQueryString
#define DdeQueryString
#define DdeReconnect
#define DdeSetQualityOfService
#define DdeSetUserHandle
#define DdeUnaccessData
#define DdeUninitialize
#define DefDlgProc
#define DefDlgProc
#define DefFrameProc
#define DefFrameProc
#define DefMDIChildProc
#define DefMDIChildProc
#define DefRawInputProc
#define DefWindowProc
#define DefWindowProc
#define DeferWindowPos
#define DeleteMenu
#define DeregisterShellHookWindow
#define DestroyAcceleratorTable
#define DestroyCaret
#define DestroyCursor
#define DestroyIcon
#define DestroyMenu
#define DestroyWindow
#define DialogBoxIndirectParam
#define DialogBoxIndirectParam
#define DialogBoxParam
#define DialogBoxParam
#define DisableProcessWindowsGhosting
#define DispatchMessage
#define DispatchMessage
#define DisplayConfigGetDeviceInfo
#define DisplayConfigSetDeviceInfo
#define DlgDirList
#define DlgDirListComboBox
#define DlgDirListComboBox
#define DlgDirList
#define DlgDirSelectComboBoxEx
#define DlgDirSelectComboBoxEx
#define DlgDirSelectEx
#define DlgDirSelectEx
#define DragDetect
#define DragObject
#define DrawAnimatedRects
#define DrawCaption
#define DrawEdge
#define DrawFocusRect
#define DrawFrame
#define DrawFrameControl
#define DrawIcon
#define DrawIconEx
#define DrawMenuBar
#define DrawState
#define DrawState
#define DrawText
#define DrawTextEx
#define DrawTextEx
#define DrawText
#define EditWndProc
#define EmptyClipboard
#define EnableMenuItem
#define EnableMouseInPointer
#define EnableScrollBar
#define EnableSessionForMMCSS
#define EnableWindow
#define EndDeferWindowPos
#define EndDialog
#define EndMenu
#define EndPaint
#define EndTask
#define EnumChildWindows
#define EnumClipboardFormats
#define EnumDesktopWindows
#define EnumDesktops
#define EnumDesktops
#define EnumDisplayDevices
#define EnumDisplayDevices
#define EnumDisplayMonitors
#define EnumDisplaySettings
#define EnumDisplaySettingsEx
#define EnumDisplaySettingsEx
#define EnumDisplaySettings
#define EnumProps
#define EnumPropsEx
#define EnumPropsEx
#define EnumProps
#define EnumThreadWindows
#define EnumWindowStations
#define EnumWindowStations
#define EnumWindows
#define EqualRect
#define EvaluateProximityToPolygon
#define EvaluateProximityToRect
#define ExcludeUpdateRgn
#define ExitWindowsEx
#define FillRect
#define FindWindow
#define FindWindowEx
#define FindWindowEx
#define FindWindow
#define FlashWindow
#define FlashWindowEx
#define FrameRect
#define FreeDDElParam
#define GetActiveWindow
#define GetAltTabInfo
#define GetAltTabInfo
#define GetAltTabInfo
#define GetAncestor
#define GetAsyncKeyState
#define GetAutoRotationState
#define GetCIMSSM
#define GetCapture
#define GetCaretBlinkTime
#define GetCaretPos
#define GetClassInfo
#define GetClassInfoEx
#define GetClassInfoEx
#define GetClassInfo
#define GetClassLong
#define GetClassLong
#define GetClassName
#define GetClassName
#define GetClassWord
#define GetClientRect
#define GetClipCursor
#define GetClipboardData
#define GetClipboardFormatName
#define GetClipboardFormatName
#define GetClipboardOwner
#define GetClipboardSequenceNumber
#define GetClipboardViewer
#define GetComboBoxInfo
#define GetCurrentInputMessageSource
#define GetCursor
#define GetCursorInfo
#define GetCursorPos
#define GetDC
#define GetDCEx
#define GetDesktopWindow
#define GetDialogBaseUnits
#define GetDisplayAutoRotationPreferences
#define GetDisplayConfigBufferSizes
#define GetDlgCtrlID
#define GetDlgItem
#define GetDlgItemInt
#define GetDlgItemText
#define GetDlgItemText
#define GetDoubleClickTime
#define GetFocus
#define GetForegroundWindow
#define GetGUIThreadInfo
#define GetGestureConfig
#define GetGestureExtraArgs
#define GetGestureInfo
#define GetGuiResources
#define GetIconInfo
#define GetIconInfoEx
#define GetIconInfoEx
#define GetInputDesktop
#define GetInputLocaleInfo
#define GetInputState
#define GetKBCodePage
#define GetKeyNameText
#define GetKeyNameText
#define GetKeyState
#define GetKeyboardLayout
#define GetKeyboardLayoutList
#define GetKeyboardLayoutName
#define GetKeyboardLayoutName
#define GetKeyboardState
#define GetKeyboardType
#define GetLastActivePopup
#define GetLastInputInfo
#define GetLayeredWindowAttributes
#define GetListBoxInfo
#define GetMenu
#define GetMenuBarInfo
#define GetMenuCheckMarkDimensions
#define GetMenuContextHelpId
#define GetMenuDefaultItem
#define GetMenuInfo
#define GetMenuItemCount
#define GetMenuItemID
#define GetMenuItemInfo
#define GetMenuItemInfo
#define GetMenuItemRect
#define GetMenuState
#define GetMenuString
#define GetMenuString
#define GetMessage
#define GetMessageExtraInfo
#define GetMessagePos
#define GetMessageTime
#define GetMessage
#define GetMonitorInfo
#define GetMonitorInfo
#define GetMouseMovePointsEx
#define GetNextDlgGroupItem
#define GetNextDlgTabItem
#define GetOpenClipboardWindow
#define GetParent
#define GetPhysicalCursorPos
#define GetPointerCursorId
#define GetPointerDevice
#define GetPointerDeviceCursors
#define GetPointerDeviceProperties
#define GetPointerDeviceRects
#define GetPointerDevices
#define GetPointerFrameInfo
#define GetPointerFrameInfoHistory
#define GetPointerFramePenInfo
#define GetPointerFramePenInfoHistory
#define GetPointerFrameTouchInfo
#define GetPointerFrameTouchInfoHistory
#define GetPointerInfo
#define GetPointerInfoHistory
#define GetPointerInputTransform
#define GetPointerPenInfo
#define GetPointerPenInfoHistory
#define GetPointerTouchInfo
#define GetPointerTouchInfoHistory
#define GetPointerType
#define GetPriorityClipboardFormat
#define GetProcessDefaultLayout
#define GetProcessWindowStation
#define GetProp
#define GetProp
#define GetQueueStatus
#define GetRawInputBuffer
#define GetRawInputData
#define GetRawInputDeviceInfo
#define GetRawInputDeviceInfo
#define GetRawInputDeviceList
#define GetRawPointerDeviceData
#define GetRegisteredRawInputDevices
#define GetScrollBarInfo
#define GetScrollInfo
#define GetScrollPos
#define GetScrollRange
#define GetShellWindow
#define GetSubMenu
#define GetSysColor
#define GetSysColorBrush
#define GetSystemMenu
#define GetSystemMetrics
#define GetTabbedTextExtent
#define GetTabbedTextExtent
#define GetThreadDesktop
#define GetTitleBarInfo
#define GetTopWindow
#define GetTouchInputInfo
#define GetUnpredictedMessagePos
#define GetUpdateRect
#define GetUpdateRgn
#define GetUpdatedClipboardFormats
#define GetUserObjectInformation
#define GetUserObjectInformation
#define GetUserObjectSecurity
#define GetWindow
#define GetWindowContextHelpId
#define GetWindowDC
#define GetWindowDisplayAffinity
#define GetWindowFeedbackSetting
#define GetWindowInfo
#define GetWindowLong
#define GetWindowLong
#define GetWindowModuleFileName
#define GetWindowModuleFileName
#define GetWindowModuleFileName
#define GetWindowPlacement
#define GetWindowRect
#define GetWindowRgn
#define GetWindowRgnBox
#define GetWindowText
#define GetWindowTextLength
#define GetWindowTextLength
#define GetWindowText
#define GetWindowThreadProcessId
#define GetWindowWord
#define GrayString
#define GrayString
#define HideCaret
#define HiliteMenuItem
#define IMPGetIME
#define IMPGetIME
#define IMPQueryIME
#define IMPQueryIME
#define IMPSetIME
#define IMPSetIME
#define ImpersonateDdeClientWindow
#define InSendMessage
#define InSendMessageEx
#define InflateRect
#define InitializeTouchInjection
#define InjectTouchInput
#define InsertMenu
#define InsertMenuItem
#define InsertMenuItem
#define InsertMenu
#define InternalGetWindowText
#define IntersectRect
#define InvalidateRect
#define InvalidateRgn
#define InvertRect
#define IsCharAlpha
#define IsCharAlphaNumeric
#define IsCharAlphaNumeric
#define IsCharAlpha
#define IsCharLower
#define IsCharLower
#define IsCharUpper
#define IsCharUpper
#define IsChild
#define IsClipboardFormatAvailable
#define IsDialogMessage
#define IsDialogMessage
#define IsDialogMessage
#define IsDlgButtonChecked
#define IsGUIThread
#define IsHungAppWindow
#define IsIconic
#define IsImmersiveProcess
#define IsInDesktopWindowBand
#define IsMenu
#define IsMouseInPointerEnabled
#define IsProcessDPIAware
#define IsRectEmpty
#define IsTouchWindow
#define IsWinEventHookInstalled
#define IsWindow
#define IsWindowEnabled
#define IsWindowUnicode
#define IsWindowVisible
#define IsWow64Message
#define IsZoomed
#define KillTimer
#define LoadAccelerators
#define LoadAccelerators
#define LoadBitmap
#define LoadBitmap
#define LoadCursor
#define LoadCursorFromFile
#define LoadCursorFromFile
#define LoadCursor
#define LoadIcon
#define LoadIcon
#define LoadImage
#define LoadImage
#define LoadKeyboardLayout
#define LoadKeyboardLayout
#define LoadMenu
#define LoadMenuIndirect
#define LoadMenuIndirect
#define LoadMenu
#define LoadString
#define LoadString
#define LockSetForegroundWindow
#define LockWindowUpdate
#define LockWorkStation
#define LogicalToPhysicalPoint
#define LogicalToPhysicalPointForPerMonitorDPI
#define LookupIconIdFromDirectory
#define LookupIconIdFromDirectoryEx
#define MapDialogRect
#define MapVirtualKey
#define MapVirtualKeyEx
#define MapVirtualKeyEx
#define MapVirtualKey
#define MapWindowPoints
#define MenuItemFromPoint
#define MessageBeep
#define MessageBox
#define MessageBoxEx
#define MessageBoxEx
#define MessageBoxIndirect
#define MessageBoxIndirect
#define MessageBoxTimeout
#define MessageBoxTimeout
#define MessageBox
#define ModifyMenu
#define ModifyMenu
#define MonitorFromPoint
#define MonitorFromRect
#define MonitorFromWindow
#define MoveWindow
#define MsgWaitForMultipleObjects
#define MsgWaitForMultipleObjectsEx
#define NotifyWinEvent
#define OemKeyScan
#define OemToChar
#define OemToCharBuff
#define OemToCharBuff
#define OemToChar
#define OffsetRect
#define OpenClipboard
#define OpenDesktop
#define OpenDesktop
#define OpenIcon
#define OpenInputDesktop
#define OpenWindowStation
#define OpenWindowStation
#define PackDDElParam
#define PackTouchHitTestingProximityEvaluation
#define PaintDesktop
#define PeekMessage
#define PeekMessage
#define PhysicalToLogicalPoint
#define PhysicalToLogicalPointForPerMonitorDPI
#define PostMessage
#define PostMessage
#define PostQuitMessage
#define PostThreadMessage
#define PostThreadMessage
#define PrintWindow
#define PrivateExtractIcons
#define PrivateExtractIcons
#define PtInRect
#define QueryDisplayConfig
#define RealChildWindowFromPoint
#define RealGetWindowClass
#define RealGetWindowClass
#define RealGetWindowClass
#define RedrawWindow
#define RegisterClass
#define RegisterClassEx
#define RegisterClassEx
#define RegisterClass
#define RegisterClipboardFormat
#define RegisterClipboardFormat
#define RegisterDeviceNotification
#define RegisterDeviceNotification
#define RegisterHotKey
#define RegisterPointerDeviceNotifications
#define RegisterPointerInputTarget
#define RegisterPowerSettingNotification
#define RegisterRawInputDevices
#define RegisterShellHookWindow
#define RegisterSuspendResumeNotification
#define RegisterTouchHitTestingWindow
#define RegisterTouchWindow
#define RegisterWindowMessage
#define RegisterWindowMessage
#define ReleaseCapture
#define ReleaseDC
#define RemoveClipboardFormatListener
#define RemoveMenu
#define RemoveProp
#define RemoveProp
#define ReplyMessage
#define ReuseDDElParam
#define ScreenToClient
#define ScrollDC
#define ScrollWindow
#define ScrollWindowEx
#define SendDlgItemMessage
#define SendDlgItemMessage
#define SendIMEMessageEx
#define SendIMEMessageEx
#define SendInput
#define SendMessage
#define SendMessageCallback
#define SendMessageCallback
#define SendMessageTimeout
#define SendMessageTimeout
#define SendMessage
#define SendNotifyMessage
#define SendNotifyMessage
#define SetActiveWindow
#define SetCapture
#define SetCaretBlinkTime
#define SetCaretPos
#define SetClassLong
#define SetClassLong
#define SetClassWord
#define SetClipboardData
#define SetClipboardViewer
#define SetCoalescableTimer
#define SetCursor
#define SetCursorPos
#define SetDebugErrorLevel
#define SetDeskWallpaper
#define SetDisplayAutoRotationPreferences
#define SetDisplayConfig
#define SetDlgItemInt
#define SetDlgItemText
#define SetDlgItemText
#define SetDoubleClickTime
#define SetFocus
#define SetForegroundWindow
#define SetGestureConfig
#define SetKeyboardState
#define SetLastErrorEx
#define SetLayeredWindowAttributes
#define SetMenu
#define SetMenuContextHelpId
#define SetMenuDefaultItem
#define SetMenuInfo
#define SetMenuItemBitmaps
#define SetMenuItemInfo
#define SetMenuItemInfo
#define SetMessageExtraInfo
#define SetMessageQueue
#define SetParent
#define SetPhysicalCursorPos
#define SetProcessDPIAware
#define SetProcessDefaultLayout
#define SetProcessRestrictionExemption
#define SetProcessWindowStation
#define SetProp
#define SetProp
#define SetRect
#define SetRectEmpty
#define SetScrollInfo
#define SetScrollPos
#define SetScrollRange
#define SetShellWindow
#define SetSysColors
#define SetSystemCursor
#define SetThreadDesktop
#define SetTimer
#define SetUserObjectInformation
#define SetUserObjectInformation
#define SetUserObjectSecurity
#define SetWinEventHook
#define SetWindowContextHelpId
#define SetWindowDisplayAffinity
#define SetWindowFeedbackSetting
#define SetWindowLong
#define SetWindowLong
#define SetWindowPlacement
#define SetWindowPos
#define SetWindowRgn
#define SetWindowText
#define SetWindowText
#define SetWindowWord
#define SetWindowsHook
#define SetWindowsHookEx
#define SetWindowsHookEx
#define SetWindowsHook
#define ShowCaret
#define ShowCursor
#define ShowOwnedPopups
#define ShowScrollBar
#define ShowSystemCursor
#define ShowWindow
#define ShowWindowAsync
#define ShutdownBlockReasonCreate
#define ShutdownBlockReasonDestroy
#define ShutdownBlockReasonQuery
#define SkipPointerFrameMessages
#define SoundSentry
#define SubtractRect
#define SwapMouseButton
#define SwitchDesktop
#define SwitchToThisWindow
#define SystemParametersInfo
#define SystemParametersInfo
#define TabbedTextOut
#define TabbedTextOut
#define TileChildWindows
#define TileWindows
#define ToAscii
#define ToAsciiEx
#define ToUnicode
#define ToUnicodeEx
#define TrackMouseEvent
#define TrackPopupMenu
#define TrackPopupMenuEx
#define TranslateAccelerator
#define TranslateAccelerator
#define TranslateAccelerator
#define TranslateMDISysAccel
#define TranslateMessage
#define UnhookWinEvent
#define UnhookWindowsHook
#define UnhookWindowsHookEx
#define UnionRect
#define UnloadKeyboardLayout
#define UnpackDDElParam
#define UnregisterClass
#define UnregisterClass
#define UnregisterDeviceNotification
#define UnregisterHotKey
#define UnregisterPointerInputTarget
#define UnregisterPowerSettingNotification
#define UnregisterSuspendResumeNotification
#define UnregisterTouchWindow
#define UpdateLayeredWindow
#define UpdateLayeredWindowIndirect
#define UpdateWindow
#define UserHandleGrantAccess
#define ValidateRect
#define ValidateRgn
#define VkKeyScan
#define VkKeyScanEx
#define VkKeyScanEx
#define VkKeyScan
#define WINNLSEnableIME
#define WINNLSGetEnableStatus
#define WINNLSGetIMEHotkey
#define WaitForInputIdle
#define WaitMessage
#define WinHelp
#define WinHelp
#define WindowFromDC
#define WindowFromPhysicalPoint
#define WindowFromPoint
#define keybd_event
#define mouse_event
#define wsprintf
#define wsprintf
#define wvsprintf
#define wvsprintf
// user32.lib end


// kernel32.lib start
#define mbol name  : @InterlockedPushListSList
#define AcquireSRWLockExclusive
#define AcquireSRWLockShared
#define ActivateActCtx
#define AddAtom
#define AddAtom
#define AddConsoleAlias
#define AddConsoleAlias
#define AddDllDirectory
#define AddIntegrityLabelToBoundaryDescriptor
#define AddLocalAlternateComputerName
#define AddLocalAlternateComputerName
#define AddRefActCtx
#define AddResourceAttributeAce
#define AddSIDToBoundaryDescriptor
#define AddScopedPolicyIDAce
#define AddSecureMemoryCacheCallback
#define AddVectoredContinueHandler
#define AddVectoredExceptionHandler
#define AllocConsole
#define AllocateUserPhysicalPages
#define AllocateUserPhysicalPagesNuma
#define AppXGetOSMaxVersionTested
#define ApplicationRecoveryFinished
#define ApplicationRecoveryInProgress
#define AreFileApisANSI
#define AssignProcessToJobObject
#define AttachConsole
#define BackupRead
#define BackupSeek
#define BackupWrite
#define BaseSetLastNTError
#define Beep
#define BeginUpdateResource
#define BeginUpdateResource
#define BindIoCompletionCallback
#define BuildCommDCB
#define BuildCommDCBAndTimeouts
#define BuildCommDCBAndTimeouts
#define BuildCommDCB
#define CallNamedPipe
#define CallNamedPipe
#define CallbackMayRunLong
#define CalloutOnFiberStack
#define CancelDeviceWakeupRequest
#define CancelIo
#define CancelIoEx
#define CancelSynchronousIo
#define CancelThreadpoolIo
#define CancelTimerQueueTimer
#define CancelWaitableTimer
#define CeipIsOptedIn
#define ChangeTimerQueueTimer
#define CheckElevation
#define CheckElevationEnabled
#define CheckNameLegalDOS8Dot3
#define CheckNameLegalDOS8Dot3
#define CheckRemoteDebuggerPresent
#define CheckTokenCapability
#define CheckTokenMembershipEx
#define ClearCommBreak
#define ClearCommError
#define CloseHandle
#define ClosePackageInfo
#define ClosePrivateNamespace
#define CloseState
#define CloseThreadpool
#define CloseThreadpoolCleanupGroup
#define CloseThreadpoolCleanupGroupMembers
#define CloseThreadpoolIo
#define CloseThreadpoolTimer
#define CloseThreadpoolWait
#define CloseThreadpoolWork
#define CommConfigDialog
#define CommConfigDialog
#define CompareFileTime
#define CompareString
#define CompareStringEx
#define CompareStringOrdinal
#define CompareString
#define ConnectNamedPipe
#define ContinueDebugEvent
#define ConvertDefaultLocale
#define ConvertFiberToThread
#define ConvertThreadToFiber
#define ConvertThreadToFiberEx
#define CopyContext
#define CopyFile2
#define CopyFile
#define CopyFileEx
#define CopyFileEx
#define CopyFileTransacted
#define CopyFileTransacted
#define CopyFile
#define CreateActCtx
#define CreateActCtx
#define CreateBoundaryDescriptor
#define CreateBoundaryDescriptor
#define CreateConsoleScreenBuffer
#define CreateDirectory
#define CreateDirectoryEx
#define CreateDirectoryEx
#define CreateDirectoryTransacted
#define CreateDirectoryTransacted
#define CreateDirectory
#define CreateEvent
#define CreateEventEx
#define CreateEventEx
#define CreateEvent
#define CreateFiber
#define CreateFiberEx
#define CreateFile2
#define CreateFile
#define CreateFileMapping
#define CreateFileMappingFromApp
#define CreateFileMappingNuma
#define CreateFileMappingNuma
#define CreateFileMapping
#define CreateFileTransacted
#define CreateFileTransacted
#define CreateFile
#define CreateHardLink
#define CreateHardLinkTransacted
#define CreateHardLinkTransacted
#define CreateHardLink
#define CreateIoCompletionPort
#define CreateJobObject
#define CreateJobObject
#define CreateJobSet
#define CreateMailslot
#define CreateMailslot
#define CreateMemoryResourceNotification
#define CreateMutex
#define CreateMutexEx
#define CreateMutexEx
#define CreateMutex
#define CreateNamedPipe
#define CreateNamedPipe
#define CreatePipe
#define CreatePrivateNamespace
#define CreatePrivateNamespace
#define CreateProcess
#define CreateProcess
#define CreateRemoteThread
#define CreateRemoteThreadEx
#define CreateSemaphore
#define CreateSemaphoreEx
#define CreateSemaphoreEx
#define CreateSemaphore
#define CreateSymbolicLink
#define CreateSymbolicLinkTransacted
#define CreateSymbolicLinkTransacted
#define CreateSymbolicLink
#define CreateTapePartition
#define CreateThread
#define CreateThreadpool
#define CreateThreadpoolCleanupGroup
#define CreateThreadpoolIo
#define CreateThreadpoolTimer
#define CreateThreadpoolWait
#define CreateThreadpoolWork
#define CreateTimerQueue
#define CreateTimerQueueTimer
#define CreateToolhelp32Snapshot
#define CreateWaitableTimer
#define CreateWaitableTimerEx
#define CreateWaitableTimerEx
#define CreateWaitableTimer
#define CtrlRoutine
#define DeactivateActCtx
#define DebugActiveProcess
#define DebugActiveProcessStop
#define DebugBreak
#define DebugBreakProcess
#define DebugSetProcessKillOnExit
#define DecodePointer
#define DecodeSystemPointer
#define DefineDosDevice
#define DefineDosDevice
#define DelayLoadFailureHook
#define DeleteAtom
#define DeleteBoundaryDescriptor
#define DeleteCriticalSection
#define DeleteFiber
#define DeleteFile
#define DeleteFileTransacted
#define DeleteFileTransacted
#define DeleteFile
#define DeleteProcThreadAttributeList
#define DeleteSynchronizationBarrier
#define DeleteTimerQueue
#define DeleteTimerQueueEx
#define DeleteTimerQueueTimer
#define DeleteVolumeMountPoint
#define DeleteVolumeMountPoint
#define DeviceIoControl
#define DisableThreadLibraryCalls
#define DisableThreadProfiling
#define DisassociateCurrentThreadFromCallback
#define DisconnectNamedPipe
#define DnsHostnameToComputerName
#define DnsHostnameToComputerNameEx
#define DnsHostnameToComputerName
#define DosDateTimeToFileTime
#define DosPathToSessionPath
#define DuplicateHandle
#define EnableThreadProfiling
#define EncodePointer
#define EncodeSystemPointer
#define EndUpdateResource
#define EndUpdateResource
#define EnterCriticalSection
#define EnterSynchronizationBarrier
#define EnumCalendarInfo
#define EnumCalendarInfoEx
#define EnumCalendarInfoExEx
#define EnumCalendarInfoEx
#define EnumCalendarInfo
#define EnumDateFormats
#define EnumDateFormatsEx
#define EnumDateFormatsExEx
#define EnumDateFormatsEx
#define EnumDateFormats
#define EnumLanguageGroupLocales
#define EnumLanguageGroupLocales
#define EnumResourceLanguages
#define EnumResourceLanguagesEx
#define EnumResourceLanguagesEx
#define EnumResourceLanguages
#define EnumResourceNames
#define EnumResourceNamesEx
#define EnumResourceNamesEx
#define EnumResourceNames
#define EnumResourceTypes
#define EnumResourceTypesEx
#define EnumResourceTypesEx
#define EnumResourceTypes
#define EnumSystemCodePages
#define EnumSystemCodePages
#define EnumSystemFirmwareTables
#define EnumSystemGeoID
#define EnumSystemLanguageGroups
#define EnumSystemLanguageGroups
#define EnumSystemLocales
#define EnumSystemLocalesEx
#define EnumSystemLocales
#define EnumTimeFormats
#define EnumTimeFormatsEx
#define EnumTimeFormats
#define EnumUILanguages
#define EnumUILanguages
#define EnumerateLocalComputerNames
#define EnumerateLocalComputerNames
#define EraseTape
#define EscapeCommFunction
#define ExitProcess
#define ExitThread
#define ExpandEnvironmentStrings
#define ExpandEnvironmentStrings
#define FatalAppExit
#define FatalAppExit
#define FatalExit
#define FileTimeToDosDateTime
#define FileTimeToLocalFileTime
#define FileTimeToSystemTime
#define FillConsoleOutputAttribute
#define FillConsoleOutputCharacter
#define FillConsoleOutputCharacter
#define FindActCtxSectionGuid
#define FindActCtxSectionString
#define FindActCtxSectionString
#define FindAtom
#define FindAtom
#define FindClose
#define FindCloseChangeNotification
#define FindFirstChangeNotification
#define FindFirstChangeNotification
#define FindFirstFile
#define FindFirstFileEx
#define FindFirstFileEx
#define FindFirstFileNameTransacted
#define FindFirstFileName
#define FindFirstFileTransacted
#define FindFirstFileTransacted
#define FindFirstFile
#define FindFirstStreamTransacted
#define FindFirstStream
#define FindFirstVolume
#define FindFirstVolumeMountPoint
#define FindFirstVolumeMountPoint
#define FindFirstVolume
#define FindNLSString
#define FindNLSStringEx
#define FindNextChangeNotification
#define FindNextFile
#define FindNextFileName
#define FindNextFile
#define FindNextStream
#define FindNextVolume
#define FindNextVolumeMountPoint
#define FindNextVolumeMountPoint
#define FindNextVolume
#define FindPackagesByPackageFamily
#define FindResource
#define FindResourceEx
#define FindResourceEx
#define FindResource
#define FindStringOrdinal
#define FindVolumeClose
#define FindVolumeMountPointClose
#define FlsAlloc
#define FlsFree
#define FlsGetValue
#define FlsSetValue
#define FlushConsoleInputBuffer
#define FlushFileBuffers
#define FlushInstructionCache
#define FlushProcessWriteBuffers
#define FlushViewOfFile
#define FoldString
#define FoldString
#define FormatApplicationUserModelId
#define FormatMessage
#define FormatMessage
#define FreeConsole
#define FreeEnvironmentStrings
#define FreeEnvironmentStrings
#define FreeLibrary
#define FreeLibraryAndExitThread
#define FreeLibraryWhenCallbackReturns
#define FreeResource
#define FreeUserPhysicalPages
#define GenerateConsoleCtrlEvent
#define GetACP
#define GetActiveProcessorCount
#define GetActiveProcessorGroupCount
#define GetAppContainerAce
#define GetAppContainerNamedObjectPath
#define GetApplicationRecoveryCallback
#define GetApplicationRestartSettings
#define GetApplicationUserModelId
#define GetAtomName
#define GetAtomName
#define GetBinaryType
#define GetBinaryType
#define GetBinaryType
#define GetCPInfo
#define GetCPInfoEx
#define GetCPInfoEx
#define GetCachedSigningLevel
#define GetCalendarInfo
#define GetCalendarInfoEx
#define GetCalendarInfo
#define GetCommConfig
#define GetCommMask
#define GetCommModemStatus
#define GetCommProperties
#define GetCommState
#define GetCommTimeouts
#define GetCommandLine
#define GetCommandLine
#define GetCompressedFileSize
#define GetCompressedFileSizeTransacted
#define GetCompressedFileSizeTransacted
#define GetCompressedFileSize
#define GetComputerName
#define GetComputerNameEx
#define GetComputerNameEx
#define GetComputerName
#define GetConsoleAlias
#define GetConsoleAliasExes
#define GetConsoleAliasExesLength
#define GetConsoleAliasExesLength
#define GetConsoleAliasExes
#define GetConsoleAlias
#define GetConsoleAliases
#define GetConsoleAliasesLength
#define GetConsoleAliasesLength
#define GetConsoleAliases
#define GetConsoleCP
#define GetConsoleCursorInfo
#define GetConsoleDisplayMode
#define GetConsoleFontSize
#define GetConsoleHistoryInfo
#define GetConsoleMode
#define GetConsoleOriginalTitle
#define GetConsoleOriginalTitle
#define GetConsoleOutputCP
#define GetConsoleProcessList
#define GetConsoleScreenBufferInfo
#define GetConsoleScreenBufferInfoEx
#define GetConsoleSelectionInfo
#define GetConsoleTitle
#define GetConsoleTitle
#define GetConsoleWindow
#define GetCurrencyFormat
#define GetCurrencyFormatEx
#define GetCurrencyFormat
#define GetCurrentActCtx
#define GetCurrentApplicationUserModelId
#define GetCurrentConsoleFont
#define GetCurrentConsoleFontEx
#define GetCurrentDirectory
#define GetCurrentDirectory
#define GetCurrentPackageFamilyName
#define GetCurrentPackageFullName
#define GetCurrentPackageId
#define GetCurrentPackageInfo
#define GetCurrentPackagePath
#define GetCurrentProcess
#define GetCurrentProcessId
#define GetCurrentProcessorNumber
#define GetCurrentProcessorNumberEx
#define GetCurrentThread
#define GetCurrentThreadId
#define GetCurrentThreadStackLimits
#define GetDateFormat
#define GetDateFormatEx
#define GetDateFormat
#define GetDefaultCommConfig
#define GetDefaultCommConfig
#define GetDevicePowerState
#define GetDiskFreeSpace
#define GetDiskFreeSpaceEx
#define GetDiskFreeSpaceEx
#define GetDiskFreeSpace
#define GetDllDirectory
#define GetDllDirectory
#define GetDriveType
#define GetDriveType
#define GetDurationFormat
#define GetDurationFormatEx
#define GetDynamicTimeZoneInformation
#define GetEnabledXStateFeatures
#define GetEnvironmentStrings
#define GetEnvironmentStrings
#define GetEnvironmentStrings
#define GetEnvironmentVariable
#define GetEnvironmentVariable
#define GetEraNameCountedString
#define GetErrorMode
#define GetExitCodeProcess
#define GetExitCodeThread
#define GetFileAttributes
#define GetFileAttributesEx
#define GetFileAttributesEx
#define GetFileAttributesTransacted
#define GetFileAttributesTransacted
#define GetFileAttributes
#define GetFileBandwidthReservation
#define GetFileInformationByHandle
#define GetFileInformationByHandleEx
#define GetFileMUIInfo
#define GetFileMUIPath
#define GetFileSize
#define GetFileSizeEx
#define GetFileTime
#define GetFileType
#define GetFinalPathNameByHandle
#define GetFinalPathNameByHandle
#define GetFirmwareEnvironmentVariable
#define GetFirmwareEnvironmentVariableEx
#define GetFirmwareEnvironmentVariableEx
#define GetFirmwareEnvironmentVariable
#define GetFirmwareType
#define GetFullPathName
#define GetFullPathNameTransacted
#define GetFullPathNameTransacted
#define GetFullPathName
#define GetGeoInfo
#define GetGeoInfo
#define GetHandleInformation
#define GetLargePageMinimum
#define GetLargestConsoleWindowSize
#define GetLastError
#define GetLocalTime
#define GetLocaleInfo
#define GetLocaleInfoEx
#define GetLocaleInfo
#define GetLogicalDriveStrings
#define GetLogicalDriveStrings
#define GetLogicalDrives
#define GetLogicalProcessorInformation
#define GetLogicalProcessorInformationEx
#define GetLongPathName
#define GetLongPathNameTransacted
#define GetLongPathNameTransacted
#define GetLongPathName
#define GetMailslotInfo
#define GetMaximumProcessorCount
#define GetMaximumProcessorGroupCount
#define GetMemoryErrorHandlingCapabilities
#define GetModuleFileName
#define GetModuleFileName
#define GetModuleHandle
#define GetModuleHandleEx
#define GetModuleHandleEx
#define GetModuleHandle
#define GetNLSVersion
#define GetNLSVersionEx
#define GetNamedPipeAttribute
#define GetNamedPipeClientComputerName
#define GetNamedPipeClientComputerName
#define GetNamedPipeClientProcessId
#define GetNamedPipeClientSessionId
#define GetNamedPipeHandleState
#define GetNamedPipeHandleState
#define GetNamedPipeInfo
#define GetNamedPipeServerProcessId
#define GetNamedPipeServerSessionId
#define GetNativeSystemInfo
#define GetNumaAvailableMemoryNode
#define GetNumaAvailableMemoryNodeEx
#define GetNumaHighestNodeNumber
#define GetNumaNodeNumberFromHandle
#define GetNumaNodeProcessorMask
#define GetNumaNodeProcessorMaskEx
#define GetNumaProcessorNode
#define GetNumaProcessorNodeEx
#define GetNumaProximityNode
#define GetNumaProximityNodeEx
#define GetNumberFormat
#define GetNumberFormatEx
#define GetNumberFormat
#define GetNumberOfConsoleInputEvents
#define GetNumberOfConsoleMouseButtons
#define GetOEMCP
#define GetOverlappedResult
#define GetOverlappedResultEx
#define GetPackageApplicationIds
#define GetPackageFamilyName
#define GetPackageFullName
#define GetPackageId
#define GetPackageInfo
#define GetPackagePath
#define GetPackagePathByFullName
#define GetPackagesByPackageFamily
#define GetPhysicallyInstalledSystemMemory
#define GetPriorityClass
#define GetPrivateProfileInt
#define GetPrivateProfileInt
#define GetPrivateProfileSection
#define GetPrivateProfileSectionNames
#define GetPrivateProfileSectionNames
#define GetPrivateProfileSection
#define GetPrivateProfileString
#define GetPrivateProfileString
#define GetPrivateProfileStruct
#define GetPrivateProfileStruct
#define GetProcAddress
#define GetProcessAffinityMask
#define GetProcessDEPPolicy
#define GetProcessGroupAffinity
#define GetProcessHandleCount
#define GetProcessHeap
#define GetProcessHeaps
#define GetProcessId
#define GetProcessIdOfThread
#define GetProcessInformation
#define GetProcessIoCounters
#define GetProcessMitigationPolicy
#define GetProcessPreferredUILanguages
#define GetProcessPriorityBoost
#define GetProcessShutdownParameters
#define GetProcessTimes
#define GetProcessVersion
#define GetProcessWorkingSetSize
#define GetProcessWorkingSetSizeEx
#define GetProcessorSystemCycleTime
#define GetProductInfo
#define GetProfileInt
#define GetProfileInt
#define GetProfileSection
#define GetProfileSection
#define GetProfileString
#define GetProfileString
#define GetQueuedCompletionStatus
#define GetQueuedCompletionStatusEx
#define GetShortPathName
#define GetShortPathName
#define GetStagedPackagePathByFullName
#define GetStartupInfo
#define GetStartupInfo
#define GetStateFolder
#define GetStdHandle
#define GetStringScripts
#define GetStringType
#define GetStringTypeEx
#define GetStringTypeEx
#define GetStringType
#define GetSystemAppDataKey
#define GetSystemDEPPolicy
#define GetSystemDefaultLCID
#define GetSystemDefaultLangID
#define GetSystemDefaultLocaleName
#define GetSystemDefaultUILanguage
#define GetSystemDirectory
#define GetSystemDirectory
#define GetSystemFileCacheSize
#define GetSystemFirmwareTable
#define GetSystemInfo
#define GetSystemPowerStatus
#define GetSystemPreferredUILanguages
#define GetSystemRegistryQuota
#define GetSystemTime
#define GetSystemTimeAdjustment
#define GetSystemTimeAsFileTime
#define GetSystemTimePreciseAsFileTime
#define GetSystemTimes
#define GetSystemWindowsDirectory
#define GetSystemWindowsDirectory
#define GetSystemWow64Directory
#define GetSystemWow64Directory
#define GetTapeParameters
#define GetTapePosition
#define GetTapeStatus
#define GetTempFileName
#define GetTempFileName
#define GetTempPath
#define GetTempPath
#define GetThreadContext
#define GetThreadErrorMode
#define GetThreadGroupAffinity
#define GetThreadIOPendingFlag
#define GetThreadId
#define GetThreadIdealProcessorEx
#define GetThreadInformation
#define GetThreadLocale
#define GetThreadPreferredUILanguages
#define GetThreadPriority
#define GetThreadPriorityBoost
#define GetThreadSelectorEntry
#define GetThreadTimes
#define GetThreadUILanguage
#define GetTickCount64
#define GetTickCount
#define GetTimeFormat
#define GetTimeFormatEx
#define GetTimeFormat
#define GetTimeZoneInformation
#define GetTimeZoneInformationForYear
#define GetUILanguageInfo
#define GetUserDefaultLCID
#define GetUserDefaultLangID
#define GetUserDefaultLocaleName
#define GetUserDefaultUILanguage
#define GetUserGeoID
#define GetUserPreferredUILanguages
#define GetVersion
#define GetVersionEx
#define GetVersionEx
#define GetVolumeInformation
#define GetVolumeInformationByHandle
#define GetVolumeInformation
#define GetVolumeNameForVolumeMountPoint
#define GetVolumeNameForVolumeMountPoint
#define GetVolumePathName
#define GetVolumePathName
#define GetVolumePathNamesForVolumeName
#define GetVolumePathNamesForVolumeName
#define GetWindowsDirectory
#define GetWindowsDirectory
#define GetWriteWatch
#define GetXStateFeaturesMask
#define GlobalAddAtom
#define GlobalAddAtomEx
#define GlobalAddAtomEx
#define GlobalAddAtom
#define GlobalAlloc
#define GlobalCompact
#define GlobalDeleteAtom
#define GlobalFindAtom
#define GlobalFindAtom
#define GlobalFix
#define GlobalFlags
#define GlobalFree
#define GlobalGetAtomName
#define GlobalGetAtomName
#define GlobalHandle
#define GlobalLock
#define GlobalMemoryStatus
#define GlobalMemoryStatusEx
#define GlobalReAlloc
#define GlobalSize
#define GlobalUnWire
#define GlobalUnfix
#define GlobalUnlock
#define GlobalWire
#define Heap32First
#define Heap32ListFirst
#define Heap32ListNext
#define Heap32Next
#define HeapAlloc
#define HeapCompact
#define HeapCreate
#define HeapDestroy
#define HeapFree
#define HeapLock
#define HeapQueryInformation
#define HeapReAlloc
#define HeapSetInformation
#define HeapSize
#define HeapSummary
#define HeapUnlock
#define HeapValidate
#define HeapWalk
#define InitAtomTable
#define InitOnceBeginInitialize
#define InitOnceComplete
#define InitOnceExecuteOnce
#define InitOnceInitialize
#define InitializeConditionVariable
#define InitializeContext
#define InitializeCriticalSection
#define InitializeCriticalSectionAndSpinCount
#define InitializeCriticalSectionEx
#define InitializeProcThreadAttributeList
#define InitializeSListHead
#define InitializeSRWLock
#define InitializeSynchronizationBarrier
#define InstallELAMCertificateInfo
#define InterlockedCompareExchange64
#define InterlockedCompareExchange
#define InterlockedDecrement
#define InterlockedExchange
#define InterlockedExchangeAdd
#define InterlockedFlushSList
#define InterlockedIncrement
#define InterlockedPopEntrySList
#define InterlockedPushEntrySList
#define InterlockedPushListSListEx
#define IsBadCodePtr
#define IsBadHugeReadPtr
#define IsBadHugeWritePtr
#define IsBadReadPtr
#define IsBadStringPtr
#define IsBadStringPtr
#define IsBadWritePtr
#define IsDBCSLeadByte
#define IsDBCSLeadByteEx
#define IsDebuggerPresent
#define IsNLSDefinedString
#define IsNativeVhdBoot
#define IsNormalizedString
#define IsProcessCritical
#define IsProcessInJob
#define IsProcessorFeaturePresent
#define IsSystemResumeAutomatic
#define IsThreadAFiber
#define IsThreadpoolTimerSet
#define IsValidCodePage
#define IsValidLanguageGroup
#define IsValidLocale
#define IsValidLocaleName
#define IsValidNLSVersion
#define IsWow64Process
#define K32EmptyWorkingSet
#define K32EnumDeviceDrivers
#define K32EnumPageFiles
#define K32EnumPageFiles
#define K32EnumProcessModules
#define K32EnumProcessModulesEx
#define K32EnumProcesses
#define K32GetDeviceDriverBaseName
#define K32GetDeviceDriverBaseName
#define K32GetDeviceDriverFileName
#define K32GetDeviceDriverFileName
#define K32GetMappedFileName
#define K32GetMappedFileName
#define K32GetModuleBaseName
#define K32GetModuleBaseName
#define K32GetModuleFileNameEx
#define K32GetModuleFileNameEx
#define K32GetModuleInformation
#define K32GetPerformanceInfo
#define K32GetProcessImageFileName
#define K32GetProcessImageFileName
#define K32GetProcessMemoryInfo
#define K32GetWsChanges
#define K32GetWsChangesEx
#define K32InitializeProcessForWsWatch
#define K32QueryWorkingSet
#define K32QueryWorkingSetEx
#define LCIDToLocaleName
#define LCMapString
#define LCMapStringEx
#define LCMapString
#define LeaveCriticalSection
#define LeaveCriticalSectionWhenCallbackReturns
#define LoadAppInitDlls
#define LoadLibrary
#define LoadLibraryEx
#define LoadLibraryEx
#define LoadLibrary
#define LoadModule
#define LoadPackagedLibrary
#define LoadResource
#define LoadStringBaseEx
#define LoadStringBase
#define LocalAlloc
#define LocalCompact
#define LocalFileTimeToFileTime
#define LocalFlags
#define LocalFree
#define LocalHandle
#define LocalLock
#define LocalReAlloc
#define LocalShrink
#define LocalSize
#define LocalUnlock
#define LocaleNameToLCID
#define LocateXStateFeature
#define LockFile
#define LockFileEx
#define LockResource
#define MapUserPhysicalPages
#define MapUserPhysicalPagesScatter
#define MapViewOfFile
#define MapViewOfFileEx
#define MapViewOfFileExNuma
#define MapViewOfFileFromApp
#define Module32First
#define Module32First
#define Module32Next
#define Module32Next
#define MoveFile
#define MoveFileEx
#define MoveFileEx
#define MoveFileTransacted
#define MoveFileTransacted
#define MoveFile
#define MoveFileWithProgress
#define MoveFileWithProgress
#define MulDiv
#define MultiByteToWideChar
#define NeedCurrentDirectoryForExePath
#define NeedCurrentDirectoryForExePath
#define NormalizeString
#define NotifyMountMgr
#define NotifyUILanguageChange
#define OOBEComplete
#define OpenEvent
#define OpenEvent
#define OpenFile
#define OpenFileById
#define OpenFileMapping
#define OpenFileMapping
#define OpenJobObject
#define OpenJobObject
#define OpenMutex
#define OpenMutex
#define OpenPackageInfoByFullName
#define OpenPrivateNamespace
#define OpenPrivateNamespace
#define OpenProcess
#define OpenSemaphore
#define OpenSemaphore
#define OpenState
#define OpenStateExplicit
#define OpenThread
#define OpenWaitableTimer
#define OpenWaitableTimer
#define OutputDebugString
#define OutputDebugString
#define PackageFamilyNameFromFullName
#define PackageFamilyNameFromId
#define PackageFullNameFromId
#define PackageIdFromFullName
#define PackageNameAndPublisherIdFromFamilyName
#define ParseApplicationUserModelId
#define PeekConsoleInput
#define PeekConsoleInput
#define PeekNamedPipe
#define PostQueuedCompletionStatus
#define PowerClearRequest
#define PowerCreateRequest
#define PowerSetRequest
#define PrefetchVirtualMemory
#define PrepareTape
#define Process32First
#define Process32First
#define Process32Next
#define Process32Next
#define ProcessIdToSessionId
#define PssCaptureSnapshot
#define PssDuplicateSnapshot
#define PssFreeSnapshot
#define PssQuerySnapshot
#define PssWalkMarkerCreate
#define PssWalkMarkerFree
#define PssWalkMarkerGetPosition
#define PssWalkMarkerRewind
#define PssWalkMarkerSeek
#define PssWalkMarkerSeekToBeginning
#define PssWalkMarkerSetPosition
#define PssWalkMarkerTell
#define PssWalkSnapshot
#define PulseEvent
#define PurgeComm
#define QueryActCtxSettings
#define QueryActCtx
#define QueryDepthSList
#define QueryDosDevice
#define QueryDosDevice
#define QueryFullProcessImageName
#define QueryFullProcessImageName
#define QueryIdleProcessorCycleTime
#define QueryIdleProcessorCycleTimeEx
#define QueryInformationJobObject
#define QueryMemoryResourceNotification
#define QueryPerformanceCounter
#define QueryPerformanceFrequency
#define QueryProcessAffinityUpdateMode
#define QueryProcessCycleTime
#define QueryProtectedPolicy
#define QueryThreadCycleTime
#define QueryThreadProfiling
#define QueryThreadpoolStackInformation
#define QueryUnbiasedInterruptTime
#define QueueUserAPC
#define QueueUserWorkItem
#define RaiseException
#define RaiseFailFastException
#define ReOpenFile
#define ReadConsole
#define ReadConsoleInput
#define ReadConsoleInput
#define ReadConsoleOutput
#define ReadConsoleOutputAttribute
#define ReadConsoleOutputCharacter
#define ReadConsoleOutputCharacter
#define ReadConsoleOutput
#define ReadConsole
#define ReadDirectoryChanges
#define ReadFile
#define ReadFileEx
#define ReadFileScatter
#define ReadProcessMemory
#define ReadThreadProfilingData
#define RegisterApplicationRecoveryCallback
#define RegisterApplicationRestart
#define RegisterBadMemoryNotification
#define RegisterWaitForInputIdle
#define RegisterWaitForSingleObject
#define RegisterWaitForSingleObjectEx
#define RegisterWaitUntilOOBECompleted
#define ReleaseActCtx
#define ReleaseMutex
#define ReleaseMutexWhenCallbackReturns
#define ReleaseSRWLockExclusive
#define ReleaseSRWLockShared
#define ReleaseSemaphore
#define ReleaseSemaphoreWhenCallbackReturns
#define RemoveDirectory
#define RemoveDirectoryTransacted
#define RemoveDirectoryTransacted
#define RemoveDirectory
#define RemoveDllDirectory
#define RemoveLocalAlternateComputerName
#define RemoveLocalAlternateComputerName
#define RemoveSecureMemoryCacheCallback
#define RemoveVectoredContinueHandler
#define RemoveVectoredExceptionHandler
#define ReplaceFile
#define ReplaceFile
#define ReplaceFile
#define ReplacePartitionUnit
#define RequestDeviceWakeup
#define RequestWakeupLatency
#define ResetEvent
#define ResetWriteWatch
#define ResolveDelayLoadedAPI
#define ResolveDelayLoadsFromDll
#define ResolveLocaleName
#define RestoreLastError
#define ResumeThread
#define RtlCaptureContext
#define RtlCaptureStackBackTrace
#define RtlFillMemory
#define RtlMoveMemory
#define RtlUnwind
#define RtlZeroMemory
#define ScrollConsoleScreenBuffer
#define ScrollConsoleScreenBuffer
#define SearchPath
#define SearchPath
#define SetCachedSigningLevel
#define SetCalendarInfo
#define SetCalendarInfo
#define SetCommBreak
#define SetCommConfig
#define SetCommMask
#define SetCommState
#define SetCommTimeouts
#define SetComputerName
#define SetComputerNameEx2
#define SetComputerNameEx
#define SetComputerNameEx
#define SetComputerName
#define SetConsoleActiveScreenBuffer
#define SetConsoleCP
#define SetConsoleCtrlHandler
#define SetConsoleCursor
#define SetConsoleCursorInfo
#define SetConsoleCursorPosition
#define SetConsoleDisplayMode
#define SetConsoleHistoryInfo
#define SetConsoleMode
#define SetConsoleOutputCP
#define SetConsoleScreenBufferInfoEx
#define SetConsoleScreenBufferSize
#define SetConsoleTextAttribute
#define SetConsoleTitle
#define SetConsoleTitle
#define SetConsoleWindowInfo
#define SetCriticalSectionSpinCount
#define SetCurrentConsoleFontEx
#define SetCurrentDirectory
#define SetCurrentDirectory
#define SetDefaultCommConfig
#define SetDefaultCommConfig
#define SetDefaultDllDirectories
#define SetDllDirectory
#define SetDllDirectory
#define SetDynamicTimeZoneInformation
#define SetEndOfFile
#define SetEnvironmentStrings
#define SetEnvironmentStrings
#define SetEnvironmentVariable
#define SetEnvironmentVariable
#define SetErrorMode
#define SetEvent
#define SetEventWhenCallbackReturns
#define SetFileApisToANSI
#define SetFileApisToOEM
#define SetFileAttributes
#define SetFileAttributesTransacted
#define SetFileAttributesTransacted
#define SetFileAttributes
#define SetFileBandwidthReservation
#define SetFileCompletionNotificationModes
#define SetFileInformationByHandle
#define SetFileIoOverlappedRange
#define SetFilePointer
#define SetFilePointerEx
#define SetFileShortName
#define SetFileShortName
#define SetFileTime
#define SetFileValidData
#define SetFirmwareEnvironmentVariable
#define SetFirmwareEnvironmentVariableEx
#define SetFirmwareEnvironmentVariableEx
#define SetFirmwareEnvironmentVariable
#define SetHandleCount
#define SetHandleInformation
#define SetInformationJobObject
#define SetLastError
#define SetLocalPrimaryComputerName
#define SetLocalPrimaryComputerName
#define SetLocalTime
#define SetLocaleInfo
#define SetLocaleInfo
#define SetMailslotInfo
#define SetMessageWaitingIndicator
#define SetNamedPipeAttribute
#define SetNamedPipeHandleState
#define SetPriorityClass
#define SetProcessAffinityMask
#define SetProcessAffinityUpdateMode
#define SetProcessDEPPolicy
#define SetProcessInformation
#define SetProcessMitigationPolicy
#define SetProcessPreferredUILanguages
#define SetProcessPriorityBoost
#define SetProcessShutdownParameters
#define SetProcessWorkingSetSize
#define SetProcessWorkingSetSizeEx
#define SetProtectedPolicy
#define SetSearchPathMode
#define SetStdHandle
#define SetStdHandleEx
#define SetSystemFileCacheSize
#define SetSystemPowerState
#define SetSystemTime
#define SetSystemTimeAdjustment
#define SetTapeParameters
#define SetTapePosition
#define SetThreadAffinityMask
#define SetThreadContext
#define SetThreadErrorMode
#define SetThreadExecutionState
#define SetThreadGroupAffinity
#define SetThreadIdealProcessor
#define SetThreadIdealProcessorEx
#define SetThreadInformation
#define SetThreadLocale
#define SetThreadPreferredUILanguages
#define SetThreadPriority
#define SetThreadPriorityBoost
#define SetThreadStackGuarantee
#define SetThreadUILanguage
#define SetThreadpoolStackInformation
#define SetThreadpoolThreadMaximum
#define SetThreadpoolThreadMinimum
#define SetThreadpoolTimer
#define SetThreadpoolTimerEx
#define SetThreadpoolWait
#define SetThreadpoolWaitEx
#define SetTimeZoneInformation
#define SetTimerQueueTimer
#define SetUnhandledExceptionFilter
#define SetUserGeoID
#define SetVolumeLabel
#define SetVolumeLabel
#define SetVolumeMountPoint
#define SetVolumeMountPoint
#define SetWaitableTimer
#define SetWaitableTimerEx
#define SetXStateFeaturesMask
#define SetupComm
#define SignalObjectAndWait
#define SizeofResource
#define Sleep
#define SleepConditionVariableCS
#define SleepConditionVariableSR
#define SleepEx
#define StartThreadpoolIo
#define SubmitThreadpoolWork
#define SuspendThread
#define SwitchToFiber
#define SwitchToThread
#define SystemTimeToFileTime
#define SystemTimeToTzSpecificLocalTime
#define SystemTimeToTzSpecificLocalTimeEx
#define TerminateJobObject
#define TerminateProcess
#define TerminateThread
#define Thread32First
#define Thread32Next
#define TlsAlloc
#define TlsFree
#define TlsGetValue
#define TlsSetValue
#define Toolhelp32ReadProcessMemory
#define TransactNamedPipe
#define TransmitCommChar
#define TryAcquireSRWLockExclusive
#define TryAcquireSRWLockShared
#define TryEnterCriticalSection
#define TrySubmitThreadpoolCallback
#define TzSpecificLocalTimeToSystemTime
#define TzSpecificLocalTimeToSystemTimeEx
#define UnhandledExceptionFilter
#define UnlockFile
#define UnlockFileEx
#define UnmapViewOfFile
#define UnmapViewOfFileEx
#define UnregisterApplicationRecoveryCallback
#define UnregisterApplicationRestart
#define UnregisterBadMemoryNotification
#define UnregisterWait
#define UnregisterWaitEx
#define UnregisterWaitUntilOOBECompleted
#define UpdateProcThreadAttribute
#define UpdateResource
#define UpdateResource
#define VerLanguageName
#define VerLanguageName
#define VerSetConditionMask
#define VerifyScripts
#define VerifyVersionInfo
#define VerifyVersionInfo
#define VirtualAlloc
#define VirtualAllocEx
#define VirtualAllocExNuma
#define VirtualFree
#define VirtualFreeEx
#define VirtualLock
#define VirtualProtect
#define VirtualProtectEx
#define VirtualQuery
#define VirtualQueryEx
#define VirtualUnlock
#define WTSGetActiveConsoleSessionId
#define WaitCommEvent
#define WaitForDebugEvent
#define WaitForMultipleObjects
#define WaitForMultipleObjectsEx
#define WaitForSingleObject
#define WaitForSingleObjectEx
#define WaitForThreadpoolIoCallbacks
#define WaitForThreadpoolTimerCallbacks
#define WaitForThreadpoolWaitCallbacks
#define WaitForThreadpoolWorkCallbacks
#define WaitNamedPipe
#define WaitNamedPipe
#define WakeAllConditionVariable
#define WakeConditionVariable
#define WerGetFlags
#define WerRegisterFile
#define WerRegisterMemoryBlock
#define WerRegisterRuntimeExceptionModule
#define WerSetFlags
#define WerUnregisterFile
#define WerUnregisterMemoryBlock
#define WerUnregisterRuntimeExceptionModule
#define WerpInitiateRemoteRecovery
#define WideCharToMultiByte
#define WinExec
#define Wow64DisableWow64FsRedirection
#define Wow64EnableWow64FsRedirection
#define Wow64GetThreadContext
#define Wow64GetThreadSelectorEntry
#define Wow64RevertWow64FsRedirection
#define Wow64SetThreadContext
#define Wow64SuspendThread
#define WriteConsole
#define WriteConsoleInput
#define WriteConsoleInput
#define WriteConsoleOutput
#define WriteConsoleOutputAttribute
#define WriteConsoleOutputCharacter
#define WriteConsoleOutputCharacter
#define WriteConsoleOutput
#define WriteConsole
#define WriteFile
#define WriteFileEx
#define WriteFileGather
#define WritePrivateProfileSection
#define WritePrivateProfileSection
#define WritePrivateProfileString
#define WritePrivateProfileString
#define WritePrivateProfileStruct
#define WritePrivateProfileStruct
#define WriteProcessMemory
#define WriteProfileSection
#define WriteProfileSection
#define WriteProfileString
#define WriteProfileString
#define WriteTapemark
#define ZombifyActCtx
#define _hread
#define _hwrite
#define _lclose
#define _lcreat
#define _llseek
#define _lopen
#define _lread
#define _lwrite
#define lstrcat
#define lstrcat
#define lstrcat
#define lstrcmp
#define lstrcmp
#define lstrcmp
#define lstrcmpi
#define lstrcmpi
#define lstrcmpi
#define lstrcpy
#define lstrcpy
#define lstrcpy
#define lstrcpyn
#define lstrcpyn
#define lstrcpyn
#define lstrlen
#define lstrlen
#define lstrlen
// kernel32.lib end


// gdi32.lib start
#define AbortDoc
#define AbortPath
#define AddFontMemResourceEx
#define AddFontResource
#define AddFontResourceEx
#define AddFontResourceEx
#define AddFontResource
#define AngleArc
#define AnimatePalette
#define Arc
#define ArcTo
#define BeginPath
#define BitBlt
#define CancelDC
#define CheckColorsInGamut
#define ChoosePixelFormat
#define Chord
#define CloseEnhMetaFile
#define CloseFigure
#define CloseMetaFile
#define ColorCorrectPalette
#define ColorMatchToTarget
#define CombineRgn
#define CombineTransform
#define CopyEnhMetaFile
#define CopyEnhMetaFile
#define CopyMetaFile
#define CopyMetaFile
#define CreateBitmap
#define CreateBitmapIndirect
#define CreateBrushIndirect
#define CreateColorSpace
#define CreateColorSpace
#define CreateCompatibleBitmap
#define CreateCompatibleDC
#define CreateDC
#define CreateDC
#define CreateDIBPatternBrush
#define CreateDIBPatternBrushPt
#define CreateDIBSection
#define CreateDIBitmap
#define CreateDiscardableBitmap
#define CreateEllipticRgn
#define CreateEllipticRgnIndirect
#define CreateEnhMetaFile
#define CreateEnhMetaFile
#define CreateFont
#define CreateFontIndirect
#define CreateFontIndirectEx
#define CreateFontIndirectEx
#define CreateFontIndirect
#define CreateFont
#define CreateHalftonePalette
#define CreateHatchBrush
#define CreateIC
#define CreateIC
#define CreateMetaFile
#define CreateMetaFile
#define CreatePalette
#define CreatePatternBrush
#define CreatePen
#define CreatePenIndirect
#define CreatePolyPolygonRgn
#define CreatePolygonRgn
#define CreateRectRgn
#define CreateRectRgnIndirect
#define CreateRoundRectRgn
#define CreateScalableFontResource
#define CreateScalableFontResource
#define CreateSolidBrush
#define D3DKMTAcquireKeyedMutex2
#define D3DKMTAcquireKeyedMutex
#define D3DKMTCacheHybridQueryValue
#define D3DKMTCheckExclusiveOwnership
#define D3DKMTCheckMonitorPowerState
#define D3DKMTCheckMultiPlaneOverlaySupport
#define D3DKMTCheckOcclusion
#define D3DKMTCheckSharedResourceAccess
#define D3DKMTCheckVidPnExclusiveOwnership
#define D3DKMTCloseAdapter
#define D3DKMTConfigureSharedResource
#define D3DKMTCreateAllocation2
#define D3DKMTCreateAllocation
#define D3DKMTCreateContext
#define D3DKMTCreateDCFromMemory
#define D3DKMTCreateDevice
#define D3DKMTCreateKeyedMutex2
#define D3DKMTCreateKeyedMutex
#define D3DKMTCreateOutputDupl
#define D3DKMTCreateOverlay
#define D3DKMTCreateSynchronizationObject2
#define D3DKMTCreateSynchronizationObject
#define D3DKMTDestroyAllocation
#define D3DKMTDestroyContext
#define D3DKMTDestroyDCFromMemory
#define D3DKMTDestroyDevice
#define D3DKMTDestroyKeyedMutex
#define D3DKMTDestroyOutputDupl
#define D3DKMTDestroyOverlay
#define D3DKMTDestroySynchronizationObject
#define D3DKMTEnumAdapters
#define D3DKMTEscape
#define D3DKMTFlipOverlay
#define D3DKMTGetCachedHybridQueryValue
#define D3DKMTGetContextInProcessSchedulingPriority
#define D3DKMTGetContextSchedulingPriority
#define D3DKMTGetDeviceState
#define D3DKMTGetDisplayModeList
#define D3DKMTGetMultisampleMethodList
#define D3DKMTGetOverlayState
#define D3DKMTGetPresentHistory
#define D3DKMTGetPresentQueueEvent
#define D3DKMTGetProcessSchedulingPriorityClass
#define D3DKMTGetRuntimeData
#define D3DKMTGetScanLine
#define D3DKMTGetSharedPrimaryHandle
#define D3DKMTGetSharedResourceAdapterLuid
#define D3DKMTInvalidateActiveVidPn
#define D3DKMTLock
#define D3DKMTNetDispGetNextChunkInfo
#define D3DKMTNetDispQueryMiracastDisplayDeviceStatus
#define D3DKMTNetDispQueryMiracastDisplayDeviceSupport
#define D3DKMTNetDispStartMiracastDisplayDevice2
#define D3DKMTNetDispStopMiracastDisplayDevice
#define D3DKMTOfferAllocations
#define D3DKMTOpenAdapterFromDeviceName
#define D3DKMTOpenAdapterFromGdiDisplayName
#define D3DKMTOpenAdapterFromHdc
#define D3DKMTOpenAdapterFromLuid
#define D3DKMTOpenKeyedMutex2
#define D3DKMTOpenKeyedMutex
#define D3DKMTOpenNtHandleFromName
#define D3DKMTOpenResource2
#define D3DKMTOpenResource
#define D3DKMTOpenResourceFromNtHandle
#define D3DKMTOpenSyncObjectFromNtHandle
#define D3DKMTOpenSynchronizationObject
#define D3DKMTOutputDuplGetFrameInfo
#define D3DKMTOutputDuplGetMetaData
#define D3DKMTOutputDuplGetPointerShapeData
#define D3DKMTOutputDuplPresent
#define D3DKMTOutputDuplReleaseFrame
#define D3DKMTPinDirectFlipResources
#define D3DKMTPollDisplayChildren
#define D3DKMTPresent
#define D3DKMTPresentMultiPlaneOverlay
#define D3DKMTQueryAdapterInfo
#define D3DKMTQueryAllocationResidency
#define D3DKMTQueryRemoteVidPnSourceFromGdiDisplayName
#define D3DKMTQueryResourceInfo
#define D3DKMTQueryResourceInfoFromNtHandle
#define D3DKMTQueryStatistics
#define D3DKMTReclaimAllocations
#define D3DKMTReleaseKeyedMutex2
#define D3DKMTReleaseKeyedMutex
#define D3DKMTReleaseProcessVidPnSourceOwners
#define D3DKMTRender
#define D3DKMTSetAllocationPriority
#define D3DKMTSetContextInProcessSchedulingPriority
#define D3DKMTSetContextSchedulingPriority
#define D3DKMTSetDisplayMode
#define D3DKMTSetDisplayPrivateDriverFormat
#define D3DKMTSetGammaRamp
#define D3DKMTSetProcessSchedulingPriorityClass
#define D3DKMTSetQueuedLimit
#define D3DKMTSetStereoEnabled
#define D3DKMTSetVidPnSourceOwner1
#define D3DKMTSetVidPnSourceOwner
#define D3DKMTShareObjects
#define D3DKMTSharedPrimaryLockNotification
#define D3DKMTSharedPrimaryUnLockNotification
#define D3DKMTSignalSynchronizationObject2
#define D3DKMTSignalSynchronizationObject
#define D3DKMTUnlock
#define D3DKMTUnpinDirectFlipResources
#define D3DKMTUpdateOverlay
#define D3DKMTWaitForIdle
#define D3DKMTWaitForSynchronizationObject2
#define D3DKMTWaitForSynchronizationObject
#define D3DKMTWaitForVerticalBlankEvent2
#define D3DKMTWaitForVerticalBlankEvent
#define DPtoLP
#define DeleteColorSpace
#define DeleteDC
#define DeleteEnhMetaFile
#define DeleteMetaFile
#define DeleteObject
#define DescribePixelFormat
#define DeviceCapabilitiesEx
#define DeviceCapabilitiesEx
#define DrawEscape
#define Ellipse
#define EnableEUDC
#define EndDoc
#define EndFormPage
#define EndPage
#define EndPath
#define EnumEnhMetaFile
#define EnumFontFamilies
#define EnumFontFamiliesEx
#define EnumFontFamiliesEx
#define EnumFontFamilies
#define EnumFonts
#define EnumFonts
#define EnumICMProfiles
#define EnumICMProfiles
#define EnumMetaFile
#define EnumObjects
#define EqualRgn
#define Escape
#define EudcLoadLink
#define EudcUnloadLink
#define ExcludeClipRect
#define ExtCreatePen
#define ExtCreateRegion
#define ExtEscape
#define ExtFloodFill
#define ExtSelectClipRgn
#define ExtTextOut
#define ExtTextOut
#define FillPath
#define FillRgn
#define FixBrushOrgEx
#define FlattenPath
#define FloodFill
#define FrameRgn
#define GdiAlphaBlend
#define GdiArtificialDecrementDriver
#define GdiComment
#define GdiDeleteSpoolFileHandle
#define GdiEndDocEMF
#define GdiEndPageEMF
#define GdiFlush
#define GdiGetBatchLimit
#define GdiGetDC
#define GdiGetDevmodeForPage
#define GdiGetPageCount
#define GdiGetPageHandle
#define GdiGetSpoolFileHandle
#define GdiGradientFill
#define GdiPlayDCScript
#define GdiPlayEMF
#define GdiPlayJournal
#define GdiPlayPageEMF
#define GdiPlayPrivatePageEMF
#define GdiPlayScript
#define GdiResetDCEMF
#define GdiSetBatchLimit
#define GdiStartDocEMF
#define GdiStartPageEMF
#define GdiTransparentBlt
#define GetArcDirection
#define GetAspectRatioFilterEx
#define GetBitmapBits
#define GetBitmapDimensionEx
#define GetBkColor
#define GetBkMode
#define GetBoundsRect
#define GetBrushOrgEx
#define GetCharABCWidths
#define GetCharABCWidthsFloat
#define GetCharABCWidthsFloat
#define GetCharABCWidthsI
#define GetCharABCWidths
#define GetCharWidth32
#define GetCharWidth32
#define GetCharWidth
#define GetCharWidthFloat
#define GetCharWidthFloat
#define GetCharWidthI
#define GetCharWidth
#define GetCharacterPlacement
#define GetCharacterPlacement
#define GetClipBox
#define GetClipRgn
#define GetColorAdjustment
#define GetColorSpace
#define GetCurrentObject
#define GetCurrentPositionEx
#define GetDCBrushColor
#define GetDCOrgEx
#define GetDCPenColor
#define GetDIBColorTable
#define GetDIBits
#define GetDeviceCaps
#define GetDeviceGammaRamp
#define GetEnhMetaFile
#define GetEnhMetaFileBits
#define GetEnhMetaFileDescription
#define GetEnhMetaFileDescription
#define GetEnhMetaFileHeader
#define GetEnhMetaFilePaletteEntries
#define GetEnhMetaFilePixelFormat
#define GetEnhMetaFile
#define GetFontAssocStatus
#define GetFontData
#define GetFontLanguageInfo
#define GetFontResourceInfo
#define GetFontUnicodeRanges
#define GetGlyphIndices
#define GetGlyphIndices
#define GetGlyphOutline
#define GetGlyphOutline
#define GetGlyphOutline
#define GetGraphicsMode
#define GetICMProfile
#define GetICMProfile
#define GetKerningPairs
#define GetKerningPairs
#define GetKerningPairs
#define GetLayout
#define GetLogColorSpace
#define GetLogColorSpace
#define GetMapMode
#define GetMetaFile
#define GetMetaFileBitsEx
#define GetMetaFile
#define GetMetaRgn
#define GetMiterLimit
#define GetNearestColor
#define GetNearestPaletteIndex
#define GetObject
#define GetObjectType
#define GetObject
#define GetOutlineTextMetrics
#define GetOutlineTextMetrics
#define GetPaletteEntries
#define GetPath
#define GetPixel
#define GetPixelFormat
#define GetPolyFillMode
#define GetROP2
#define GetRandomRgn
#define GetRasterizerCaps
#define GetRegionData
#define GetRelAbs
#define GetRgnBox
#define GetStockObject
#define GetStretchBltMode
#define GetSystemPaletteEntries
#define GetSystemPaletteUse
#define GetTextAlign
#define GetTextCharacterExtra
#define GetTextCharset
#define GetTextCharsetInfo
#define GetTextColor
#define GetTextExtentExPoint
#define GetTextExtentExPointI
#define GetTextExtentExPoint
#define GetTextExtentPoint32
#define GetTextExtentPoint32
#define GetTextExtentPoint
#define GetTextExtentPointI
#define GetTextExtentPoint
#define GetTextFace
#define GetTextFace
#define GetTextMetrics
#define GetTextMetrics
#define GetViewportExtEx
#define GetViewportOrgEx
#define GetWinMetaFileBits
#define GetWindowExtEx
#define GetWindowOrgEx
#define GetWorldTransform
#define IntersectClipRect
#define InvertRgn
#define LPtoDP
#define LineDD
#define LineTo
#define MaskBlt
#define ModifyWorldTransform
#define MoveToEx
#define OffsetClipRgn
#define OffsetRgn
#define OffsetViewportOrgEx
#define OffsetWindowOrgEx
#define PaintRgn
#define PatBlt
#define PathToRegion
#define Pie
#define PlayEnhMetaFile
#define PlayEnhMetaFileRecord
#define PlayMetaFile
#define PlayMetaFileRecord
#define PlgBlt
#define PolyBezier
#define PolyBezierTo
#define PolyDraw
#define PolyPolygon
#define PolyPolyline
#define PolyTextOut
#define PolyTextOut
#define Polygon
#define Polyline
#define PolylineTo
#define PtInRegion
#define PtVisible
#define RealizePalette
#define RectInRegion
#define RectVisible
#define Rectangle
#define RemoveFontMemResourceEx
#define RemoveFontResource
#define RemoveFontResourceEx
#define RemoveFontResourceEx
#define RemoveFontResource
#define ResetDC
#define ResetDC
#define ResizePalette
#define RestoreDC
#define RoundRect
#define SaveDC
#define ScaleViewportExtEx
#define ScaleWindowExtEx
#define SelectBrushLocal
#define SelectClipPath
#define SelectClipRgn
#define SelectFontLocal
#define SelectObject
#define SelectPalette
#define SetAbortProc
#define SetArcDirection
#define SetBitmapBits
#define SetBitmapDimensionEx
#define SetBkColor
#define SetBkMode
#define SetBoundsRect
#define SetBrushOrgEx
#define SetColorAdjustment
#define SetColorSpace
#define SetDCBrushColor
#define SetDCPenColor
#define SetDIBColorTable
#define SetDIBits
#define SetDIBitsToDevice
#define SetDeviceGammaRamp
#define SetEnhMetaFileBits
#define SetFontEnumeration
#define SetGraphicsMode
#define SetICMMode
#define SetICMProfile
#define SetICMProfile
#define SetLayout
#define SetMagicColors
#define SetMapMode
#define SetMapperFlags
#define SetMetaFileBitsEx
#define SetMetaRgn
#define SetMiterLimit
#define SetPaletteEntries
#define SetPixel
#define SetPixelFormat
#define SetPixelV
#define SetPolyFillMode
#define SetROP2
#define SetRectRgn
#define SetRelAbs
#define SetStretchBltMode
#define SetSystemPaletteUse
#define SetTextAlign
#define SetTextCharacterExtra
#define SetTextColor
#define SetTextJustification
#define SetViewportExtEx
#define SetViewportOrgEx
#define SetWinMetaFileBits
#define SetWindowExtEx
#define SetWindowOrgEx
#define SetWorldTransform
#define StartDoc
#define StartDoc
#define StartFormPage
#define StartPage
#define StretchBlt
#define StretchDIBits
#define StrokeAndFillPath
#define StrokePath
#define SwapBuffers
#define TextOut
#define TextOut
#define TranslateCharsetInfo
#define UnrealizeObject
#define UpdateColors
#define UpdateICMRegKey
#define UpdateICMRegKey
#define WidenPath
#define gdiPlaySpoolStream
// gdi32.lib end

