# -*- coding:gbk -*-
# uncompyle6 version 2.10.0
# Python bytecode 3.4 (3310)
# Decompiled from: Python 3.4.0 (v3.4.0:04f714765c13, Mar 16 2014, 19:24:06) [MSC v.1600 32 bit (Intel)]
# Embedded file name: D:\PlcService1200\PlcServiceUI.py
# Compiled at: 2015-08-25 14:23:16
from PyQt4 import QtCore, QtGui
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:

    def _fromUtf8(s):
        return s


try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)


except AttributeError:

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8('MainWindow'))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8('centralwidget'))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 541))
        self.groupBox.setObjectName(_fromUtf8('groupBox'))
        self.show_plc_ip = QtGui.QComboBox(self.groupBox)
        self.show_plc_ip.setGeometry(QtCore.QRect(10, 20, 361, 22))
        self.show_plc_ip.setObjectName(_fromUtf8('show_plc_ip'))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 40, 191, 471))
        self.layoutWidget.setObjectName(_fromUtf8('layoutWidget'))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8('verticalLayout_3'))
        self.show_plc_val_1 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_1.setObjectName(_fromUtf8('show_plc_val_1'))
        self.verticalLayout_3.addWidget(self.show_plc_val_1)
        self.show_plc_val_2 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_2.setObjectName(_fromUtf8('show_plc_val_2'))
        self.verticalLayout_3.addWidget(self.show_plc_val_2)
        self.show_plc_val_3 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_3.setObjectName(_fromUtf8('show_plc_val_3'))
        self.verticalLayout_3.addWidget(self.show_plc_val_3)
        self.show_plc_val_4 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_4.setObjectName(_fromUtf8('show_plc_val_4'))
        self.verticalLayout_3.addWidget(self.show_plc_val_4)
        self.show_plc_val_5 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_5.setObjectName(_fromUtf8('show_plc_val_5'))
        self.verticalLayout_3.addWidget(self.show_plc_val_5)
        self.show_plc_val_6 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_6.setObjectName(_fromUtf8('show_plc_val_6'))
        self.verticalLayout_3.addWidget(self.show_plc_val_6)
        self.show_plc_val_7 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_7.setObjectName(_fromUtf8('show_plc_val_7'))
        self.verticalLayout_3.addWidget(self.show_plc_val_7)
        self.show_plc_val_8 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_8.setObjectName(_fromUtf8('show_plc_val_8'))
        self.verticalLayout_3.addWidget(self.show_plc_val_8)
        self.show_plc_val_9 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_9.setObjectName(_fromUtf8('show_plc_val_9'))
        self.verticalLayout_3.addWidget(self.show_plc_val_9)
        self.show_plc_val_10 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_10.setObjectName(_fromUtf8('show_plc_val_10'))
        self.verticalLayout_3.addWidget(self.show_plc_val_10)
        self.show_plc_val_11 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_11.setObjectName(_fromUtf8('show_plc_val_11'))
        self.verticalLayout_3.addWidget(self.show_plc_val_11)
        self.show_plc_val_12 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_12.setObjectName(_fromUtf8('show_plc_val_12'))
        self.verticalLayout_3.addWidget(self.show_plc_val_12)
        self.show_plc_val_13 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_13.setObjectName(_fromUtf8('show_plc_val_13'))
        self.verticalLayout_3.addWidget(self.show_plc_val_13)
        self.show_plc_val_14 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_14.setObjectName(_fromUtf8('show_plc_val_14'))
        self.verticalLayout_3.addWidget(self.show_plc_val_14)
        self.show_plc_val_15 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_15.setObjectName(_fromUtf8('show_plc_val_15'))
        self.verticalLayout_3.addWidget(self.show_plc_val_15)
        self.show_plc_val_16 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_16.setObjectName(_fromUtf8('show_plc_val_16'))
        self.verticalLayout_3.addWidget(self.show_plc_val_16)
        self.show_plc_val_17 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_17.setObjectName(_fromUtf8('show_plc_val_17'))
        self.verticalLayout_3.addWidget(self.show_plc_val_17)
        self.show_plc_val_18 = QtGui.QLineEdit(self.layoutWidget)
        self.show_plc_val_18.setObjectName(_fromUtf8('show_plc_val_18'))
        self.verticalLayout_3.addWidget(self.show_plc_val_18)
        self.update_show_plc_addr = QtGui.QPushButton(self.groupBox)
        self.update_show_plc_addr.setGeometry(QtCore.QRect(10, 510, 361, 23))
        self.update_show_plc_addr.setObjectName(_fromUtf8('update_show_plc_addr'))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 40, 191, 471))
        self.layoutWidget1.setObjectName(_fromUtf8('layoutWidget1'))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8('verticalLayout'))
        self.show_plc_addr_1 = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_plc_addr_1.sizePolicy().hasHeightForWidth())
        self.show_plc_addr_1.setSizePolicy(sizePolicy)
        self.show_plc_addr_1.setObjectName(_fromUtf8('show_plc_addr_1'))
        self.verticalLayout.addWidget(self.show_plc_addr_1)
        self.show_plc_addr_2 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_2.setObjectName(_fromUtf8('show_plc_addr_2'))
        self.verticalLayout.addWidget(self.show_plc_addr_2)
        self.show_plc_addr_3 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_3.setObjectName(_fromUtf8('show_plc_addr_3'))
        self.verticalLayout.addWidget(self.show_plc_addr_3)
        self.show_plc_addr_4 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_4.setObjectName(_fromUtf8('show_plc_addr_4'))
        self.verticalLayout.addWidget(self.show_plc_addr_4)
        self.show_plc_addr_5 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_5.setObjectName(_fromUtf8('show_plc_addr_5'))
        self.verticalLayout.addWidget(self.show_plc_addr_5)
        self.show_plc_addr_6 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_6.setObjectName(_fromUtf8('show_plc_addr_6'))
        self.verticalLayout.addWidget(self.show_plc_addr_6)
        self.show_plc_addr_7 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_7.setObjectName(_fromUtf8('show_plc_addr_7'))
        self.verticalLayout.addWidget(self.show_plc_addr_7)
        self.show_plc_addr_8 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_8.setObjectName(_fromUtf8('show_plc_addr_8'))
        self.verticalLayout.addWidget(self.show_plc_addr_8)
        self.show_plc_addr_9 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_9.setObjectName(_fromUtf8('show_plc_addr_9'))
        self.verticalLayout.addWidget(self.show_plc_addr_9)
        self.show_plc_addr_10 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_10.setObjectName(_fromUtf8('show_plc_addr_10'))
        self.verticalLayout.addWidget(self.show_plc_addr_10)
        self.show_plc_addr_11 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_11.setObjectName(_fromUtf8('show_plc_addr_11'))
        self.verticalLayout.addWidget(self.show_plc_addr_11)
        self.show_plc_addr_12 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_12.setObjectName(_fromUtf8('show_plc_addr_12'))
        self.verticalLayout.addWidget(self.show_plc_addr_12)
        self.show_plc_addr_13 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_13.setObjectName(_fromUtf8('show_plc_addr_13'))
        self.verticalLayout.addWidget(self.show_plc_addr_13)
        self.show_plc_addr_14 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_14.setObjectName(_fromUtf8('show_plc_addr_14'))
        self.verticalLayout.addWidget(self.show_plc_addr_14)
        self.show_plc_addr_15 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_15.setObjectName(_fromUtf8('show_plc_addr_15'))
        self.verticalLayout.addWidget(self.show_plc_addr_15)
        self.show_plc_addr_16 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_16.setObjectName(_fromUtf8('show_plc_addr_16'))
        self.verticalLayout.addWidget(self.show_plc_addr_16)
        self.show_plc_addr_17 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_17.setObjectName(_fromUtf8('show_plc_addr_17'))
        self.verticalLayout.addWidget(self.show_plc_addr_17)
        self.show_plc_addr_18 = QtGui.QLineEdit(self.layoutWidget1)
        self.show_plc_addr_18.setObjectName(_fromUtf8('show_plc_addr_18'))
        self.verticalLayout.addWidget(self.show_plc_addr_18)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 10, 381, 541))
        self.groupBox_2.setObjectName(_fromUtf8('groupBox_2'))
        self.write_plc_ip = QtGui.QComboBox(self.groupBox_2)
        self.write_plc_ip.setGeometry(QtCore.QRect(10, 20, 361, 22))
        self.write_plc_ip.setObjectName(_fromUtf8('write_plc_ip'))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(190, 40, 191, 471))
        self.layoutWidget_2.setObjectName(_fromUtf8('layoutWidget_2'))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8('verticalLayout_4'))
        self.write_plc_val_1 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_1.setObjectName(_fromUtf8('write_plc_val_1'))
        self.verticalLayout_4.addWidget(self.write_plc_val_1)
        self.write_plc_val_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_2.setObjectName(_fromUtf8('write_plc_val_2'))
        self.verticalLayout_4.addWidget(self.write_plc_val_2)
        self.write_plc_val_3 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_3.setObjectName(_fromUtf8('write_plc_val_3'))
        self.verticalLayout_4.addWidget(self.write_plc_val_3)
        self.write_plc_val_4 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_4.setObjectName(_fromUtf8('write_plc_val_4'))
        self.verticalLayout_4.addWidget(self.write_plc_val_4)
        self.write_plc_val_5 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_5.setObjectName(_fromUtf8('write_plc_val_5'))
        self.verticalLayout_4.addWidget(self.write_plc_val_5)
        self.write_plc_val_6 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_6.setObjectName(_fromUtf8('write_plc_val_6'))
        self.verticalLayout_4.addWidget(self.write_plc_val_6)
        self.write_plc_val_7 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_7.setObjectName(_fromUtf8('write_plc_val_7'))
        self.verticalLayout_4.addWidget(self.write_plc_val_7)
        self.write_plc_val_8 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_8.setObjectName(_fromUtf8('write_plc_val_8'))
        self.verticalLayout_4.addWidget(self.write_plc_val_8)
        self.write_plc_val_9 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_9.setObjectName(_fromUtf8('write_plc_val_9'))
        self.verticalLayout_4.addWidget(self.write_plc_val_9)
        self.write_plc_val_10 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_10.setObjectName(_fromUtf8('write_plc_val_10'))
        self.verticalLayout_4.addWidget(self.write_plc_val_10)
        self.write_plc_val_11 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_11.setObjectName(_fromUtf8('write_plc_val_11'))
        self.verticalLayout_4.addWidget(self.write_plc_val_11)
        self.write_plc_val_12 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_12.setObjectName(_fromUtf8('write_plc_val_12'))
        self.verticalLayout_4.addWidget(self.write_plc_val_12)
        self.write_plc_val_13 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_13.setObjectName(_fromUtf8('write_plc_val_13'))
        self.verticalLayout_4.addWidget(self.write_plc_val_13)
        self.write_plc_val_14 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_14.setObjectName(_fromUtf8('write_plc_val_14'))
        self.verticalLayout_4.addWidget(self.write_plc_val_14)
        self.write_plc_val_15 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_15.setObjectName(_fromUtf8('write_plc_val_15'))
        self.verticalLayout_4.addWidget(self.write_plc_val_15)
        self.write_plc_val_16 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_16.setObjectName(_fromUtf8('write_plc_val_16'))
        self.verticalLayout_4.addWidget(self.write_plc_val_16)
        self.write_plc_val_17 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_17.setObjectName(_fromUtf8('write_plc_val_17'))
        self.verticalLayout_4.addWidget(self.write_plc_val_17)
        self.write_plc_val_18 = QtGui.QLineEdit(self.layoutWidget_2)
        self.write_plc_val_18.setObjectName(_fromUtf8('write_plc_val_18'))
        self.verticalLayout_4.addWidget(self.write_plc_val_18)
        self.submit_write_vals = QtGui.QPushButton(self.groupBox_2)
        self.submit_write_vals.setGeometry(QtCore.QRect(10, 510, 361, 23))
        self.submit_write_vals.setObjectName(_fromUtf8('submit_write_vals'))
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 40, 191, 471))
        self.layoutWidget_3.setObjectName(_fromUtf8('layoutWidget_3'))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8('verticalLayout_2'))
        self.write_plc_addr_1 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_1.setObjectName(_fromUtf8('write_plc_addr_1'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_1)
        self.write_plc_addr_2 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_2.setObjectName(_fromUtf8('write_plc_addr_2'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_2)
        self.write_plc_addr_3 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_3.setObjectName(_fromUtf8('write_plc_addr_3'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_3)
        self.write_plc_addr_4 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_4.setObjectName(_fromUtf8('write_plc_addr_4'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_4)
        self.write_plc_addr_5 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_5.setObjectName(_fromUtf8('write_plc_addr_5'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_5)
        self.write_plc_addr_6 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_6.setObjectName(_fromUtf8('write_plc_addr_6'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_6)
        self.write_plc_addr_7 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_7.setObjectName(_fromUtf8('write_plc_addr_7'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_7)
        self.write_plc_addr_8 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_8.setObjectName(_fromUtf8('write_plc_addr_8'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_8)
        self.write_plc_addr_9 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_9.setObjectName(_fromUtf8('write_plc_addr_9'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_9)
        self.write_plc_addr_10 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_10.setObjectName(_fromUtf8('write_plc_addr_10'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_10)
        self.write_plc_addr_11 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_11.setObjectName(_fromUtf8('write_plc_addr_11'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_11)
        self.write_plc_addr_12 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_12.setObjectName(_fromUtf8('write_plc_addr_12'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_12)
        self.write_plc_addr_13 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_13.setObjectName(_fromUtf8('write_plc_addr_13'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_13)
        self.write_plc_addr_14 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_14.setObjectName(_fromUtf8('write_plc_addr_14'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_14)
        self.write_plc_addr_15 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_15.setObjectName(_fromUtf8('write_plc_addr_15'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_15)
        self.write_plc_addr_16 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_16.setObjectName(_fromUtf8('write_plc_addr_16'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_16)
        self.write_plc_addr_17 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_17.setObjectName(_fromUtf8('write_plc_addr_17'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_17)
        self.write_plc_addr_18 = QtGui.QLineEdit(self.layoutWidget_3)
        self.write_plc_addr_18.setObjectName(_fromUtf8('write_plc_addr_18'))
        self.verticalLayout_2.addWidget(self.write_plc_addr_18)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName(_fromUtf8('menubar'))
        self.menu_program = QtGui.QMenu(self.menubar)
        self.menu_program.setObjectName(_fromUtf8('menu_program'))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName(_fromUtf8('menu_help'))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setToolTip(_fromUtf8(''))
        self.statusbar.setStatusTip(_fromUtf8(''))
        self.statusbar.setObjectName(_fromUtf8('statusbar'))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Help = QtGui.QAction(MainWindow)
        self.action_Help.setObjectName(_fromUtf8('action_Help'))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8('action_About'))
        self.action_Exit = QtGui.QAction(MainWindow)
        self.action_Exit.setObjectName(_fromUtf8('action_Exit'))
        self.action_conn_PLC = QtGui.QAction(MainWindow)
        self.action_conn_PLC.setObjectName(_fromUtf8('action_conn_PLC'))
        self.action_close_PLC = QtGui.QAction(MainWindow)
        self.action_close_PLC.setObjectName(_fromUtf8('action_close_PLC'))
        self.menu_program.addAction(self.action_conn_PLC)
        self.menu_program.addAction(self.action_close_PLC)
        self.menu_program.addSeparator()
        self.menu_program.addAction(self.action_Exit)
        self.menu_help.addAction(self.action_Help)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.action_About)
        self.menubar.addAction(self.menu_program.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate('MainWindow', '多路PLC通讯服务端', None))
        self.groupBox.setTitle(_translate('MainWindow', '查看监控变量', None))
        self.update_show_plc_addr.setText(_translate('MainWindow', '更新被监控的PLC变量', None))
        self.groupBox_2.setTitle(_translate('MainWindow', '向PLC写入变量', None))
        self.submit_write_vals.setText(_translate('MainWindow', '写入新值到PLC变量', None))
        self.menu_program.setTitle(_translate('MainWindow', '程序', None))
        self.menu_help.setTitle(_translate('MainWindow', '帮助', None))
        self.action_Help.setText(_translate('MainWindow', '帮助', None))
        self.action_About.setText(_translate('MainWindow', '关于', None))
        self.action_Exit.setText(_translate('MainWindow', '退出程序', None))
        self.action_conn_PLC.setText(_translate('MainWindow', '连接PLC', None))
        self.action_close_PLC.setText(_translate('MainWindow', '断开PLC', None))


if __name__ == '__main__':
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
